import type { AppLocale } from "./localeConfig";

export interface PublicCatalogBrowseUiCopy {
  readonly allAuthorsLabel: string;
  readonly allCollectionsLabel: string;
  readonly allLicensesLabel: string;
  readonly authorLabel: string;
  readonly clearFiltersLabel: string;
  readonly collectionLabel: string;
  readonly filtersLabel: string;
  readonly languageLabel: string;
  readonly licenseLabel: string;
  readonly nextPageLabel: string;
  readonly noResultsLabel: string;
  readonly paginationLabel: string;
  readonly pageStatusTemplate: string;
  readonly previousPageLabel: string;
  readonly resultCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
  readonly searchLabel: string;
  readonly searchPlaceholder: string;
  readonly showFiltersLabel: string;
  readonly sortLabel: string;
  readonly sortNewestLabel: string;
  readonly sortRelevanceLabel: string;
  readonly sortTitleLabel: string;
  readonly topicLabel: string;
}

export interface PublicCatalogUiCopy {
  readonly breadcrumbLabel: string;
  readonly browse: PublicCatalogBrowseUiCopy;
  readonly byLabel: string;
  readonly cardBackLabel: string;
  readonly cardFrontLabel: string;
  readonly cardPreviewsHeading: string;
  readonly cardCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
  readonly cardsLabel: string;
  readonly contentWarningLabel: string;
  readonly constructionNoticeBody: string;
  readonly constructionNoticeLabel: string;
  readonly constructionNoticeTitle: string;
  readonly coverPlaceholderLabel: string;
  readonly descriptionHeading: string;
  readonly emptyLabel: string;
  readonly installLabel: string;
  readonly intro: string;
  readonly languagesLabel: string;
  readonly licenseLabel: string;
  readonly navigationLabel: string;
  readonly noCardPreviewsLabel: string;
  readonly publishedLabel: string;
  readonly tagsLabel: string;
  readonly title: string;
  readonly topicsLabel: string;
  readonly versionLabel: string;
}

const PUBLIC_CATALOG_COPY_BY_LOCALE: Readonly<
  Record<AppLocale, PublicCatalogUiCopy>
> = {
  en: {
    breadcrumbLabel: "Catalog",
    browse: {
      allAuthorsLabel: "All authors",
      allCollectionsLabel: "All collections",
      allLicensesLabel: "All licenses",
      authorLabel: "Author",
      clearFiltersLabel: "Clear filters",
      collectionLabel: "Collection",
      filtersLabel: "Filters",
      languageLabel: "Content languages",
      licenseLabel: "License",
      nextPageLabel: "Next page",
      noResultsLabel: "No packages match these filters.",
      paginationLabel: "Catalog pages",
      pageStatusTemplate: "Page {page} of {total}",
      previousPageLabel: "Previous page",
      resultCountTemplates: {
        zero: "{count} packages",
        one: "{count} package",
        two: "{count} packages",
        few: "{count} packages",
        many: "{count} packages",
        other: "{count} packages",
      },
      searchLabel: "Search packages",
      searchPlaceholder: "Title, topic, author, or language",
      showFiltersLabel: "Search and filters",
      sortLabel: "Sort by",
      sortNewestLabel: "Newest",
      sortRelevanceLabel: "Relevance",
      sortTitleLabel: "Title",
      topicLabel: "Topics",
    },
    byLabel: "By",
    cardBackLabel: "Back",
    cardFrontLabel: "Front",
    cardPreviewsHeading: "Card previews",
    cardCountTemplates: {
      zero: "{count} cards",
      one: "{count} card",
      two: "{count} cards",
      few: "{count} cards",
      many: "{count} cards",
      other: "{count} cards",
    },
    cardsLabel: "Cards",
    contentWarningLabel: "Content warning",
    constructionNoticeBody:
      "Ready-to-use flashcard decks will be available here soon.",
    constructionNoticeLabel: "Catalog update",
    constructionNoticeTitle: "This page is under construction",
    coverPlaceholderLabel: "Cover preview unavailable",
    descriptionHeading: "About this package",
    emptyLabel: "No packages have been published yet.",
    installLabel: "Install in Flashcards",
    intro: "Browse public flashcard packages shared by the community.",
    languagesLabel: "Languages",
    licenseLabel: "License",
    navigationLabel: "Catalog",
    noCardPreviewsLabel: "This package has no cards to preview.",
    publishedLabel: "Published",
    tagsLabel: "Tags",
    title: "Public flashcard catalog",
    topicsLabel: "Topics",
    versionLabel: "Version",
  },
  es: {
    breadcrumbLabel: "Catálogo",
    browse: {
      allAuthorsLabel: "Todos los autores",
      allCollectionsLabel: "Todas las colecciones",
      allLicensesLabel: "Todas las licencias",
      authorLabel: "Autor",
      clearFiltersLabel: "Borrar filtros",
      collectionLabel: "Colección",
      filtersLabel: "Filtros",
      languageLabel: "Idiomas del contenido",
      licenseLabel: "Licencia",
      nextPageLabel: "Página siguiente",
      noResultsLabel: "Ningún paquete coincide con estos filtros.",
      paginationLabel: "Páginas del catálogo",
      pageStatusTemplate: "Página {page} de {total}",
      previousPageLabel: "Página anterior",
      resultCountTemplates: {
        zero: "{count} paquetes",
        one: "{count} paquete",
        two: "{count} paquetes",
        few: "{count} paquetes",
        many: "{count} paquetes",
        other: "{count} paquetes",
      },
      searchLabel: "Buscar paquetes",
      searchPlaceholder: "Título, tema, autor o idioma",
      showFiltersLabel: "Búsqueda y filtros",
      sortLabel: "Ordenar por",
      sortNewestLabel: "Más recientes",
      sortRelevanceLabel: "Relevancia",
      sortTitleLabel: "Título",
      topicLabel: "Temas",
    },
    byLabel: "Por",
    cardBackLabel: "Reverso",
    cardFrontLabel: "Anverso",
    cardPreviewsHeading: "Vista previa de tarjetas",
    cardCountTemplates: {
      zero: "{count} tarjetas",
      one: "{count} tarjeta",
      two: "{count} tarjetas",
      few: "{count} tarjetas",
      many: "{count} tarjetas",
      other: "{count} tarjetas",
    },
    cardsLabel: "Tarjetas",
    contentWarningLabel: "Advertencia de contenido",
    constructionNoticeBody:
      "Pronto encontrarás aquí mazos de tarjetas listos para usar.",
    constructionNoticeLabel: "Novedades del catálogo",
    constructionNoticeTitle: "Esta página está en construcción",
    coverPlaceholderLabel: "Vista previa de portada no disponible",
    descriptionHeading: "Sobre este paquete",
    emptyLabel: "Todavía no se ha publicado ningún paquete.",
    installLabel: "Instalar en Flashcards",
    intro: "Explora paquetes públicos de tarjetas compartidos por la comunidad.",
    languagesLabel: "Idiomas",
    licenseLabel: "Licencia",
    navigationLabel: "Catálogo",
    noCardPreviewsLabel: "Este paquete no tiene tarjetas para mostrar.",
    publishedLabel: "Publicado",
    tagsLabel: "Etiquetas",
    title: "Catálogo público de tarjetas",
    topicsLabel: "Temas",
    versionLabel: "Versión",
  },
  ar: {
    breadcrumbLabel: "الكتالوج",
    browse: {
      allAuthorsLabel: "كل المؤلفين",
      allCollectionsLabel: "كل المجموعات",
      allLicensesLabel: "كل التراخيص",
      authorLabel: "المؤلف",
      clearFiltersLabel: "مسح عوامل التصفية",
      collectionLabel: "المجموعة",
      filtersLabel: "عوامل التصفية",
      languageLabel: "لغات المحتوى",
      licenseLabel: "الترخيص",
      nextPageLabel: "الصفحة التالية",
      noResultsLabel: "لا توجد حزم تطابق عوامل التصفية هذه.",
      paginationLabel: "صفحات الكتالوج",
      pageStatusTemplate: "الصفحة {page} من {total}",
      previousPageLabel: "الصفحة السابقة",
      resultCountTemplates: {
        zero: "{count} حزم",
        one: "حزمة واحدة",
        two: "حزمتان",
        few: "{count} حزم",
        many: "{count} حزمة",
        other: "{count} حزمة",
      },
      searchLabel: "البحث عن حزم",
      searchPlaceholder: "العنوان أو الموضوع أو المؤلف أو اللغة",
      showFiltersLabel: "البحث وعوامل التصفية",
      sortLabel: "الترتيب حسب",
      sortNewestLabel: "الأحدث",
      sortRelevanceLabel: "الصلة",
      sortTitleLabel: "العنوان",
      topicLabel: "الموضوعات",
    },
    byLabel: "بواسطة",
    cardBackLabel: "الخلف",
    cardFrontLabel: "الأمام",
    cardPreviewsHeading: "معاينات البطاقات",
    cardCountTemplates: {
      zero: "{count} بطاقات",
      one: "بطاقة واحدة",
      two: "بطاقتان",
      few: "{count} بطاقات",
      many: "{count} بطاقة",
      other: "{count} بطاقة",
    },
    cardsLabel: "البطاقات",
    contentWarningLabel: "تحذير بشأن المحتوى",
    constructionNoticeBody:
      "ستجد هنا قريبًا مجموعات بطاقات تعليمية جاهزة للاستخدام.",
    constructionNoticeLabel: "تحديث الكتالوج",
    constructionNoticeTitle: "هذه الصفحة قيد الإنشاء",
    coverPlaceholderLabel: "معاينة الغلاف غير متاحة",
    descriptionHeading: "حول هذه الحزمة",
    emptyLabel: "لم تُنشر أي حزم بعد.",
    installLabel: "التثبيت في Flashcards",
    intro: "تصفح حزم البطاقات التعليمية العامة التي يشاركها المجتمع.",
    languagesLabel: "اللغات",
    licenseLabel: "الترخيص",
    navigationLabel: "الكتالوج",
    noCardPreviewsLabel: "لا تحتوي هذه الحزمة على بطاقات لمعاينتها.",
    publishedLabel: "تاريخ النشر",
    tagsLabel: "الوسوم",
    title: "كتالوج البطاقات التعليمية العام",
    topicsLabel: "الموضوعات",
    versionLabel: "الإصدار",
  },
  de: {
    breadcrumbLabel: "Katalog",
    browse: {
      allAuthorsLabel: "Alle Autoren",
      allCollectionsLabel: "Alle Sammlungen",
      allLicensesLabel: "Alle Lizenzen",
      authorLabel: "Autor",
      clearFiltersLabel: "Filter zurücksetzen",
      collectionLabel: "Sammlung",
      filtersLabel: "Filter",
      languageLabel: "Inhaltssprachen",
      licenseLabel: "Lizenz",
      nextPageLabel: "Nächste Seite",
      noResultsLabel: "Keine Pakete entsprechen diesen Filtern.",
      paginationLabel: "Katalogseiten",
      pageStatusTemplate: "Seite {page} von {total}",
      previousPageLabel: "Vorherige Seite",
      resultCountTemplates: {
        zero: "{count} Pakete",
        one: "{count} Paket",
        two: "{count} Pakete",
        few: "{count} Pakete",
        many: "{count} Pakete",
        other: "{count} Pakete",
      },
      searchLabel: "Pakete suchen",
      searchPlaceholder: "Titel, Thema, Autor oder Sprache",
      showFiltersLabel: "Suche und Filter",
      sortLabel: "Sortieren nach",
      sortNewestLabel: "Neueste",
      sortRelevanceLabel: "Relevanz",
      sortTitleLabel: "Titel",
      topicLabel: "Themen",
    },
    byLabel: "Von",
    cardBackLabel: "Rückseite",
    cardFrontLabel: "Vorderseite",
    cardPreviewsHeading: "Kartenvorschau",
    cardCountTemplates: {
      zero: "{count} Karten",
      one: "{count} Karte",
      two: "{count} Karten",
      few: "{count} Karten",
      many: "{count} Karten",
      other: "{count} Karten",
    },
    cardsLabel: "Karten",
    contentWarningLabel: "Inhaltswarnung",
    constructionNoticeBody:
      "Bald findest du hier sofort einsatzbereite Lernkartensätze.",
    constructionNoticeLabel: "Katalog-Update",
    constructionNoticeTitle: "Diese Seite wird gerade erstellt",
    coverPlaceholderLabel: "Covervorschau nicht verfügbar",
    descriptionHeading: "Über dieses Paket",
    emptyLabel: "Es wurden noch keine Pakete veröffentlicht.",
    installLabel: "In Flashcards installieren",
    intro: "Entdecke öffentliche Lernkartenpakete aus der Community.",
    languagesLabel: "Sprachen",
    licenseLabel: "Lizenz",
    navigationLabel: "Katalog",
    noCardPreviewsLabel: "Dieses Paket enthält keine Karten zur Vorschau.",
    publishedLabel: "Veröffentlicht",
    tagsLabel: "Tags",
    title: "Öffentlicher Lernkartenkatalog",
    topicsLabel: "Themen",
    versionLabel: "Version",
  },
  hi: {
    breadcrumbLabel: "कैटलॉग",
    browse: {
      allAuthorsLabel: "सभी लेखक",
      allCollectionsLabel: "सभी संग्रह",
      allLicensesLabel: "सभी लाइसेंस",
      authorLabel: "लेखक",
      clearFiltersLabel: "फ़िल्टर हटाएँ",
      collectionLabel: "संग्रह",
      filtersLabel: "फ़िल्टर",
      languageLabel: "सामग्री की भाषाएँ",
      licenseLabel: "लाइसेंस",
      nextPageLabel: "अगला पृष्ठ",
      noResultsLabel: "इन फ़िल्टर से कोई पैकेज नहीं मिला।",
      paginationLabel: "कैटलॉग पृष्ठ",
      pageStatusTemplate: "पृष्ठ {page}, कुल {total}",
      previousPageLabel: "पिछला पृष्ठ",
      resultCountTemplates: {
        zero: "{count} पैकेज",
        one: "{count} पैकेज",
        two: "{count} पैकेज",
        few: "{count} पैकेज",
        many: "{count} पैकेज",
        other: "{count} पैकेज",
      },
      searchLabel: "पैकेज खोजें",
      searchPlaceholder: "शीर्षक, विषय, लेखक या भाषा",
      showFiltersLabel: "खोज और फ़िल्टर",
      sortLabel: "क्रम",
      sortNewestLabel: "सबसे नए",
      sortRelevanceLabel: "प्रासंगिकता",
      sortTitleLabel: "शीर्षक",
      topicLabel: "विषय",
    },
    byLabel: "लेखक",
    cardBackLabel: "पीछे",
    cardFrontLabel: "सामने",
    cardPreviewsHeading: "कार्ड पूर्वावलोकन",
    cardCountTemplates: {
      zero: "{count} कार्ड",
      one: "{count} कार्ड",
      two: "{count} कार्ड",
      few: "{count} कार्ड",
      many: "{count} कार्ड",
      other: "{count} कार्ड",
    },
    cardsLabel: "कार्ड",
    contentWarningLabel: "सामग्री चेतावनी",
    constructionNoticeBody:
      "जल्द ही यहाँ इस्तेमाल के लिए तैयार फ़्लैशकार्ड डेक मिलेंगे।",
    constructionNoticeLabel: "कैटलॉग अपडेट",
    constructionNoticeTitle: "यह पेज अभी तैयार किया जा रहा है",
    coverPlaceholderLabel: "कवर पूर्वावलोकन उपलब्ध नहीं है",
    descriptionHeading: "इस पैकेज के बारे में",
    emptyLabel: "अभी तक कोई पैकेज प्रकाशित नहीं हुआ है।",
    installLabel: "Flashcards में इंस्टॉल करें",
    intro: "समुदाय द्वारा साझा किए गए सार्वजनिक फ़्लैशकार्ड पैकेज देखें।",
    languagesLabel: "भाषाएँ",
    licenseLabel: "लाइसेंस",
    navigationLabel: "कैटलॉग",
    noCardPreviewsLabel: "इस पैकेज में पूर्वावलोकन के लिए कोई कार्ड नहीं है।",
    publishedLabel: "प्रकाशित",
    tagsLabel: "टैग",
    title: "सार्वजनिक फ़्लैशकार्ड कैटलॉग",
    topicsLabel: "विषय",
    versionLabel: "संस्करण",
  },
  ja: {
    breadcrumbLabel: "カタログ",
    browse: {
      allAuthorsLabel: "すべての作成者",
      allCollectionsLabel: "すべてのコレクション",
      allLicensesLabel: "すべてのライセンス",
      authorLabel: "作成者",
      clearFiltersLabel: "フィルターをクリア",
      collectionLabel: "コレクション",
      filtersLabel: "フィルター",
      languageLabel: "コンテンツの言語",
      licenseLabel: "ライセンス",
      nextPageLabel: "次のページ",
      noResultsLabel: "この条件に一致するパッケージはありません。",
      paginationLabel: "カタログのページ",
      pageStatusTemplate: "{total}ページ中{page}ページ",
      previousPageLabel: "前のページ",
      resultCountTemplates: {
        zero: "{count}件のパッケージ",
        one: "{count}件のパッケージ",
        two: "{count}件のパッケージ",
        few: "{count}件のパッケージ",
        many: "{count}件のパッケージ",
        other: "{count}件のパッケージ",
      },
      searchLabel: "パッケージを検索",
      searchPlaceholder: "タイトル、トピック、作成者、言語",
      showFiltersLabel: "検索とフィルター",
      sortLabel: "並び順",
      sortNewestLabel: "新着順",
      sortRelevanceLabel: "関連度順",
      sortTitleLabel: "タイトル順",
      topicLabel: "トピック",
    },
    byLabel: "作成者",
    cardBackLabel: "裏面",
    cardFrontLabel: "表面",
    cardPreviewsHeading: "カードのプレビュー",
    cardCountTemplates: {
      zero: "{count}枚のカード",
      one: "{count}枚のカード",
      two: "{count}枚のカード",
      few: "{count}枚のカード",
      many: "{count}枚のカード",
      other: "{count}枚のカード",
    },
    cardsLabel: "カード",
    contentWarningLabel: "コンテンツに関する注意",
    constructionNoticeBody:
      "まもなく、すぐに使えるフラッシュカードデッキをここで公開します。",
    constructionNoticeLabel: "カタログ更新情報",
    constructionNoticeTitle: "このページは現在準備中です",
    coverPlaceholderLabel: "カバーのプレビューは利用できません",
    descriptionHeading: "このパッケージについて",
    emptyLabel: "公開済みのパッケージはまだありません。",
    installLabel: "Flashcards にインストール",
    intro: "コミュニティが共有した公開フラッシュカードパッケージを探せます。",
    languagesLabel: "言語",
    licenseLabel: "ライセンス",
    navigationLabel: "カタログ",
    noCardPreviewsLabel: "このパッケージにはプレビューできるカードがありません。",
    publishedLabel: "公開日",
    tagsLabel: "タグ",
    title: "公開フラッシュカードカタログ",
    topicsLabel: "トピック",
    versionLabel: "バージョン",
  },
  ru: {
    breadcrumbLabel: "Каталог",
    browse: {
      allAuthorsLabel: "Все авторы",
      allCollectionsLabel: "Все коллекции",
      allLicensesLabel: "Все лицензии",
      authorLabel: "Автор",
      clearFiltersLabel: "Сбросить фильтры",
      collectionLabel: "Коллекция",
      filtersLabel: "Фильтры",
      languageLabel: "Языки содержимого",
      licenseLabel: "Лицензия",
      nextPageLabel: "Следующая страница",
      noResultsLabel: "Нет пакетов, соответствующих этим фильтрам.",
      paginationLabel: "Страницы каталога",
      pageStatusTemplate: "Страница {page} из {total}",
      previousPageLabel: "Предыдущая страница",
      resultCountTemplates: {
        zero: "{count} пакетов",
        one: "{count} пакет",
        two: "{count} пакета",
        few: "{count} пакета",
        many: "{count} пакетов",
        other: "{count} пакета",
      },
      searchLabel: "Поиск пакетов",
      searchPlaceholder: "Название, тема, автор или язык",
      showFiltersLabel: "Поиск и фильтры",
      sortLabel: "Сортировка",
      sortNewestLabel: "Сначала новые",
      sortRelevanceLabel: "По релевантности",
      sortTitleLabel: "По названию",
      topicLabel: "Темы",
    },
    byLabel: "Автор",
    cardBackLabel: "Оборотная сторона",
    cardFrontLabel: "Лицевая сторона",
    cardPreviewsHeading: "Предпросмотр карточек",
    cardCountTemplates: {
      zero: "{count} карточек",
      one: "{count} карточка",
      two: "{count} карточки",
      few: "{count} карточки",
      many: "{count} карточек",
      other: "{count} карточки",
    },
    cardsLabel: "Карточки",
    contentWarningLabel: "Предупреждение о содержании",
    constructionNoticeBody:
      "Скоро здесь появятся готовые к использованию колоды карточек.",
    constructionNoticeLabel: "Обновление каталога",
    constructionNoticeTitle: "Эта страница находится в разработке",
    coverPlaceholderLabel: "Предпросмотр обложки недоступен",
    descriptionHeading: "Об этом пакете",
    emptyLabel: "Опубликованных пакетов пока нет.",
    installLabel: "Установить во Flashcards",
    intro: "Просматривайте общедоступные пакеты карточек от сообщества.",
    languagesLabel: "Языки",
    licenseLabel: "Лицензия",
    navigationLabel: "Каталог",
    noCardPreviewsLabel: "В этом пакете нет карточек для предпросмотра.",
    publishedLabel: "Опубликовано",
    tagsLabel: "Теги",
    title: "Открытый каталог карточек",
    topicsLabel: "Темы",
    versionLabel: "Версия",
  },
  zh: {
    breadcrumbLabel: "目录",
    browse: {
      allAuthorsLabel: "所有作者",
      allCollectionsLabel: "所有合集",
      allLicensesLabel: "所有许可证",
      authorLabel: "作者",
      clearFiltersLabel: "清除筛选条件",
      collectionLabel: "合集",
      filtersLabel: "筛选条件",
      languageLabel: "内容语言",
      licenseLabel: "许可证",
      nextPageLabel: "下一页",
      noResultsLabel: "没有符合这些筛选条件的卡包。",
      paginationLabel: "目录页面",
      pageStatusTemplate: "第 {page} 页，共 {total} 页",
      previousPageLabel: "上一页",
      resultCountTemplates: {
        zero: "{count} 个卡包",
        one: "{count} 个卡包",
        two: "{count} 个卡包",
        few: "{count} 个卡包",
        many: "{count} 个卡包",
        other: "{count} 个卡包",
      },
      searchLabel: "搜索卡包",
      searchPlaceholder: "标题、主题、作者或语言",
      showFiltersLabel: "搜索和筛选",
      sortLabel: "排序方式",
      sortNewestLabel: "最新",
      sortRelevanceLabel: "相关度",
      sortTitleLabel: "标题",
      topicLabel: "主题",
    },
    byLabel: "作者",
    cardBackLabel: "背面",
    cardFrontLabel: "正面",
    cardPreviewsHeading: "卡片预览",
    cardCountTemplates: {
      zero: "{count}张卡片",
      one: "{count}张卡片",
      two: "{count}张卡片",
      few: "{count}张卡片",
      many: "{count}张卡片",
      other: "{count}张卡片",
    },
    cardsLabel: "卡片",
    contentWarningLabel: "内容警告",
    constructionNoticeBody: "这里很快会上线可直接使用的闪卡牌组。",
    constructionNoticeLabel: "目录更新",
    constructionNoticeTitle: "此页面正在建设中",
    coverPlaceholderLabel: "封面预览不可用",
    descriptionHeading: "关于此卡包",
    emptyLabel: "尚未发布任何卡包。",
    installLabel: "安装到 Flashcards",
    intro: "浏览社区分享的公开闪卡包。",
    languagesLabel: "语言",
    licenseLabel: "许可证",
    navigationLabel: "目录",
    noCardPreviewsLabel: "此卡包没有可预览的卡片。",
    publishedLabel: "发布日期",
    tagsLabel: "标签",
    title: "公开闪卡目录",
    topicsLabel: "主题",
    versionLabel: "版本",
  },
};

export function getPublicCatalogUiCopy(
  locale: AppLocale,
): PublicCatalogUiCopy {
  return PUBLIC_CATALOG_COPY_BY_LOCALE[locale];
}
