import type { AppLocale } from "./localeConfig";

export interface PublicCatalogBrowseUiCopy {
  readonly allAuthorsLabel: string;
  readonly allCollectionsLabel: string;
  readonly allLanguagesLabel: string;
  readonly authorLabel: string;
  readonly authorSearchLabel: string;
  readonly authorSearchPlaceholder: string;
  readonly clearFiltersLabel: string;
  readonly collectionLabel: string;
  readonly collectionSearchLabel: string;
  readonly collectionSearchPlaceholder: string;
  readonly filtersLabel: string;
  readonly languageLabel: string;
  readonly languageSearchLabel: string;
  readonly languageSearchPlaceholder: string;
  readonly nextPageLabel: string;
  readonly noAuthorsFoundLabel: string;
  readonly noCollectionsFoundLabel: string;
  readonly noLanguagesFoundLabel: string;
  readonly noResultsLabel: string;
  readonly paginationLabel: string;
  readonly pageStatusTemplate: string;
  readonly pickerCloseLabel: string;
  readonly pickerDoneLabel: string;
  readonly previousPageLabel: string;
  readonly resultCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
  readonly searchLabel: string;
  readonly searchPlaceholder: string;
  readonly showFiltersLabel: string;
  readonly sortLabel: string;
  readonly sortNewestLabel: string;
  readonly sortRelevanceLabel: string;
  readonly sortTitleLabel: string;
}

export interface PublicCatalogUiCopy {
  readonly breadcrumbLabel: string;
  readonly browse: PublicCatalogBrowseUiCopy;
  readonly byLabel: string;
  readonly cardBackLabel: string;
  readonly cardFrontLabel: string;
  readonly cardHeadingTemplate: string;
  readonly cardPreviewsHeading: string;
  readonly cardCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
  readonly cardsLabel: string;
  readonly contentWarningLabel: string;
  readonly coverPlaceholderLabel: string;
  readonly deckDetailsHeading: string;
  readonly descriptionHeading: string;
  readonly emptyLabel: string;
  readonly installHelper: string;
  readonly installLabel: string;
  readonly intro: string;
  readonly lastUpdatedLabel: string;
  readonly languagesLabel: string;
  readonly levelLabel: string;
  readonly licenseLabel: string;
  readonly navigationLabel: string;
  readonly noCardPreviewsLabel: string;
  readonly publishedLabel: string;
  readonly similarDecksHeading: string;
  readonly subjectLabel: string;
  readonly tagsLabel: string;
  readonly title: string;
  readonly versionLabel: string;
}

const PUBLIC_CATALOG_COPY_BY_LOCALE: Readonly<
  Record<AppLocale, PublicCatalogUiCopy>
> = {
  en: {
    breadcrumbLabel: "Catalog",
    browse: {
      allAuthorsLabel: "All authors",
      allCollectionsLabel: "All collections",
      allLanguagesLabel: "All languages",
      authorLabel: "Author",
      authorSearchLabel: "Search authors",
      authorSearchPlaceholder: "Author name or identifier",
      clearFiltersLabel: "Clear filters",
      collectionLabel: "Collection",
      collectionSearchLabel: "Search collections",
      collectionSearchPlaceholder: "Collection name or identifier",
      filtersLabel: "Filters",
      languageLabel: "Audience languages",
      languageSearchLabel: "Search languages",
      languageSearchPlaceholder: "Language code",
      nextPageLabel: "Next page",
      noAuthorsFoundLabel: "No authors found.",
      noCollectionsFoundLabel: "No collections found.",
      noLanguagesFoundLabel: "No languages found.",
      noResultsLabel: "No decks match these filters.",
      paginationLabel: "Catalog pages",
      pageStatusTemplate: "Page {page} of {total}",
      pickerCloseLabel: "Close",
      pickerDoneLabel: "Done",
      previousPageLabel: "Previous page",
      resultCountTemplates: {
        zero: "{count} decks",
        one: "{count} deck",
        two: "{count} decks",
        few: "{count} decks",
        many: "{count} decks",
        other: "{count} decks",
      },
      searchLabel: "Search decks",
      searchPlaceholder: "Title, author, collection, or audience language",
      showFiltersLabel: "Search and filters",
      sortLabel: "Sort by",
      sortNewestLabel: "Newest",
      sortRelevanceLabel: "Relevance",
      sortTitleLabel: "Title",
    },
    byLabel: "By author",
    cardBackLabel: "Answer",
    cardFrontLabel: "Question",
    cardHeadingTemplate: "Card {number}",
    cardPreviewsHeading: "Cards in this deck",
    cardCountTemplates: {
      zero: "{count} cards",
      one: "{count} card",
      two: "{count} cards",
      few: "{count} cards",
      many: "{count} cards",
      other: "{count} cards",
    },
    cardsLabel: "Cards",
    contentWarningLabel: "Content warning",
    coverPlaceholderLabel: "Cover preview unavailable",
    deckDetailsHeading: "Deck details",
    descriptionHeading: "About this deck",
    emptyLabel: "No decks have been published yet.",
    installHelper: "Nibomo opens so you can start studying.",
    installLabel: "Study this deck for free",
    intro: "Browse public flashcard decks shared by the community.",
    lastUpdatedLabel: "Last updated",
    languagesLabel: "Audience languages",
    levelLabel: "Level",
    licenseLabel: "License",
    navigationLabel: "Catalog",
    noCardPreviewsLabel: "This deck has no cards.",
    publishedLabel: "Published",
    similarDecksHeading: "Similar decks",
    subjectLabel: "Subject",
    tagsLabel: "Tags",
    title: "Public flashcard catalog",
    versionLabel: "Version",
  },
  es: {
    breadcrumbLabel: "Catálogo",
    browse: {
      allAuthorsLabel: "Todos los autores",
      allCollectionsLabel: "Todas las colecciones",
      allLanguagesLabel: "Todos los idiomas",
      authorLabel: "Autor",
      authorSearchLabel: "Buscar autores",
      authorSearchPlaceholder: "Nombre o identificador del autor",
      clearFiltersLabel: "Borrar filtros",
      collectionLabel: "Colección",
      collectionSearchLabel: "Buscar colecciones",
      collectionSearchPlaceholder: "Nombre o identificador de la colección",
      filtersLabel: "Filtros",
      languageLabel: "Idiomas del público",
      languageSearchLabel: "Buscar idiomas",
      languageSearchPlaceholder: "Código de idioma",
      nextPageLabel: "Página siguiente",
      noAuthorsFoundLabel: "No se encontraron autores.",
      noCollectionsFoundLabel: "No se encontraron colecciones.",
      noLanguagesFoundLabel: "No se encontraron idiomas.",
      noResultsLabel: "Ningún mazo coincide con estos filtros.",
      paginationLabel: "Páginas del catálogo",
      pageStatusTemplate: "Página {page} de {total}",
      pickerCloseLabel: "Cerrar",
      pickerDoneLabel: "Listo",
      previousPageLabel: "Página anterior",
      resultCountTemplates: {
        zero: "{count} mazos",
        one: "{count} mazo",
        two: "{count} mazos",
        few: "{count} mazos",
        many: "{count} mazos",
        other: "{count} mazos",
      },
      searchLabel: "Buscar mazos",
      searchPlaceholder: "Título, autor, colección o idioma del público",
      showFiltersLabel: "Búsqueda y filtros",
      sortLabel: "Ordenar por",
      sortNewestLabel: "Más recientes",
      sortRelevanceLabel: "Relevancia",
      sortTitleLabel: "Título",
    },
    byLabel: "Por el autor",
    cardBackLabel: "Respuesta",
    cardFrontLabel: "Pregunta",
    cardHeadingTemplate: "Tarjeta {number}",
    cardPreviewsHeading: "Tarjetas de este mazo",
    cardCountTemplates: {
      zero: "{count} tarjetas",
      one: "{count} tarjeta",
      two: "{count} tarjetas",
      few: "{count} tarjetas",
      many: "{count} tarjetas",
      other: "{count} tarjetas",
    },
    cardsLabel: "Tarjetas",
    contentWarningLabel: "Advertencia de contenido",
    coverPlaceholderLabel: "Vista previa de portada no disponible",
    deckDetailsHeading: "Detalles del mazo",
    descriptionHeading: "Sobre este mazo",
    emptyLabel: "Todavía no se ha publicado ningún mazo.",
    installHelper: "Nibomo se abrirá para que puedas empezar a estudiar.",
    installLabel: "Estudia este mazo gratis",
    intro: "Explora mazos públicos de tarjetas compartidos por la comunidad.",
    lastUpdatedLabel: "Última actualización",
    languagesLabel: "Idiomas del público",
    levelLabel: "Nivel",
    licenseLabel: "Licencia",
    navigationLabel: "Catálogo",
    noCardPreviewsLabel: "Este mazo no tiene tarjetas.",
    publishedLabel: "Publicado",
    similarDecksHeading: "Mazos similares",
    subjectLabel: "Materia",
    tagsLabel: "Etiquetas",
    title: "Catálogo público de tarjetas",
    versionLabel: "Versión",
  },
  ar: {
    breadcrumbLabel: "الكتالوج",
    browse: {
      allAuthorsLabel: "كل المؤلفين",
      allCollectionsLabel: "كل المجموعات",
      allLanguagesLabel: "كل اللغات",
      authorLabel: "المؤلف",
      authorSearchLabel: "البحث عن مؤلفين",
      authorSearchPlaceholder: "اسم المؤلف أو المعرّف",
      clearFiltersLabel: "مسح عوامل التصفية",
      collectionLabel: "المجموعة",
      collectionSearchLabel: "البحث عن مجموعات",
      collectionSearchPlaceholder: "اسم المجموعة أو المعرّف",
      filtersLabel: "عوامل التصفية",
      languageLabel: "لغات الجمهور",
      languageSearchLabel: "البحث عن لغات",
      languageSearchPlaceholder: "رمز اللغة",
      nextPageLabel: "الصفحة التالية",
      noAuthorsFoundLabel: "لم يتم العثور على مؤلفين.",
      noCollectionsFoundLabel: "لم يتم العثور على مجموعات.",
      noLanguagesFoundLabel: "لم يتم العثور على لغات.",
      noResultsLabel: "لا توجد رزم تطابق عوامل التصفية هذه.",
      paginationLabel: "صفحات الكتالوج",
      pageStatusTemplate: "الصفحة {page} من {total}",
      pickerCloseLabel: "إغلاق",
      pickerDoneLabel: "تم",
      previousPageLabel: "الصفحة السابقة",
      resultCountTemplates: {
        zero: "{count} رزم",
        one: "رزمة واحدة",
        two: "رزمتان",
        few: "{count} رزم",
        many: "{count} رزمة",
        other: "{count} رزمة",
      },
      searchLabel: "البحث عن رزم",
      searchPlaceholder: "العنوان أو المؤلف أو المجموعة أو لغة الجمهور",
      showFiltersLabel: "البحث وعوامل التصفية",
      sortLabel: "الترتيب حسب",
      sortNewestLabel: "الأحدث",
      sortRelevanceLabel: "الصلة",
      sortTitleLabel: "العنوان",
    },
    byLabel: "من إعداد",
    cardBackLabel: "الإجابة",
    cardFrontLabel: "السؤال",
    cardHeadingTemplate: "البطاقة {number}",
    cardPreviewsHeading: "بطاقات هذه الرزمة",
    cardCountTemplates: {
      zero: "{count} بطاقات",
      one: "بطاقة واحدة",
      two: "بطاقتان",
      few: "{count} بطاقات",
      many: "{count} بطاقة",
      other: "{count} بطاقة",
    },
    cardsLabel: "البطاقات",
    contentWarningLabel: "تحذير بشأن المحتوى",
    coverPlaceholderLabel: "معاينة الغلاف غير متاحة",
    deckDetailsHeading: "تفاصيل الرزمة",
    descriptionHeading: "حول هذه الرزمة",
    emptyLabel: "لم تُنشر أي رزم بعد.",
    installHelper: "سيفتح تطبيق Nibomo لتبدأ الدراسة.",
    installLabel: "ادرس هذه الرزمة مجانًا",
    intro: "تصفح رزم البطاقات التعليمية العامة التي يشاركها المجتمع.",
    lastUpdatedLabel: "آخر تحديث",
    languagesLabel: "لغات الجمهور",
    levelLabel: "المستوى",
    licenseLabel: "الترخيص",
    navigationLabel: "الكتالوج",
    noCardPreviewsLabel: "لا تحتوي هذه الرزمة على بطاقات.",
    publishedLabel: "تاريخ النشر",
    similarDecksHeading: "رزم مشابهة",
    subjectLabel: "المادة",
    tagsLabel: "الوسوم",
    title: "كتالوج البطاقات التعليمية العام",
    versionLabel: "الإصدار",
  },
  de: {
    breadcrumbLabel: "Katalog",
    browse: {
      allAuthorsLabel: "Alle Autoren",
      allCollectionsLabel: "Alle Sammlungen",
      allLanguagesLabel: "Alle Sprachen",
      authorLabel: "Autor",
      authorSearchLabel: "Autoren suchen",
      authorSearchPlaceholder: "Name oder Kennung des Autors",
      clearFiltersLabel: "Filter zurücksetzen",
      collectionLabel: "Sammlung",
      collectionSearchLabel: "Sammlungen suchen",
      collectionSearchPlaceholder: "Name oder Kennung der Sammlung",
      filtersLabel: "Filter",
      languageLabel: "Zielgruppensprachen",
      languageSearchLabel: "Sprachen suchen",
      languageSearchPlaceholder: "Sprachcode",
      nextPageLabel: "Nächste Seite",
      noAuthorsFoundLabel: "Keine Autoren gefunden.",
      noCollectionsFoundLabel: "Keine Sammlungen gefunden.",
      noLanguagesFoundLabel: "Keine Sprachen gefunden.",
      noResultsLabel: "Keine Lernkartensets entsprechen diesen Filtern.",
      paginationLabel: "Katalogseiten",
      pageStatusTemplate: "Seite {page} von {total}",
      pickerCloseLabel: "Schließen",
      pickerDoneLabel: "Fertig",
      previousPageLabel: "Vorherige Seite",
      resultCountTemplates: {
        zero: "{count} Lernkartensets",
        one: "{count} Lernkartenset",
        two: "{count} Lernkartensets",
        few: "{count} Lernkartensets",
        many: "{count} Lernkartensets",
        other: "{count} Lernkartensets",
      },
      searchLabel: "Lernkartensets suchen",
      searchPlaceholder: "Titel, Autor, Sammlung oder Zielgruppensprache",
      showFiltersLabel: "Suche und Filter",
      sortLabel: "Sortieren nach",
      sortNewestLabel: "Neueste",
      sortRelevanceLabel: "Relevanz",
      sortTitleLabel: "Titel",
    },
    byLabel: "Von",
    cardBackLabel: "Antwort",
    cardFrontLabel: "Frage",
    cardHeadingTemplate: "Karte {number}",
    cardPreviewsHeading: "Karten in diesem Lernkartenset",
    cardCountTemplates: {
      zero: "{count} Karten",
      one: "{count} Karte",
      two: "{count} Karten",
      few: "{count} Karten",
      many: "{count} Karten",
      other: "{count} Karten",
    },
    cardsLabel: "Karten",
    contentWarningLabel: "Inhaltswarnung",
    coverPlaceholderLabel: "Covervorschau nicht verfügbar",
    deckDetailsHeading: "Details zum Lernkartenset",
    descriptionHeading: "Über dieses Lernkartenset",
    emptyLabel: "Es wurden noch keine Lernkartensets veröffentlicht.",
    installHelper: "Nibomo wird geöffnet, damit du mit dem Lernen beginnen kannst.",
    installLabel: "Mit diesem Lernkartenset kostenlos lernen",
    intro: "Entdecke öffentliche Lernkartensets aus der Community.",
    lastUpdatedLabel: "Zuletzt aktualisiert",
    languagesLabel: "Zielgruppensprachen",
    levelLabel: "Niveau",
    licenseLabel: "Lizenz",
    navigationLabel: "Katalog",
    noCardPreviewsLabel: "Dieses Lernkartenset enthält keine Karten.",
    publishedLabel: "Veröffentlicht",
    similarDecksHeading: "Ähnliche Lernkartensets",
    subjectLabel: "Fach",
    tagsLabel: "Tags",
    title: "Öffentlicher Lernkartenkatalog",
    versionLabel: "Version",
  },
  hi: {
    breadcrumbLabel: "कैटलॉग",
    browse: {
      allAuthorsLabel: "सभी लेखक",
      allCollectionsLabel: "सभी संग्रह",
      allLanguagesLabel: "सभी भाषाएँ",
      authorLabel: "लेखक",
      authorSearchLabel: "लेखक खोजें",
      authorSearchPlaceholder: "लेखक का नाम या पहचानकर्ता",
      clearFiltersLabel: "फ़िल्टर हटाएँ",
      collectionLabel: "संग्रह",
      collectionSearchLabel: "संग्रह खोजें",
      collectionSearchPlaceholder: "संग्रह का नाम या पहचानकर्ता",
      filtersLabel: "फ़िल्टर",
      languageLabel: "लक्षित शिक्षार्थियों की भाषाएँ",
      languageSearchLabel: "भाषाएँ खोजें",
      languageSearchPlaceholder: "भाषा कोड",
      nextPageLabel: "अगला पृष्ठ",
      noAuthorsFoundLabel: "कोई लेखक नहीं मिला।",
      noCollectionsFoundLabel: "कोई संग्रह नहीं मिला।",
      noLanguagesFoundLabel: "कोई भाषा नहीं मिली।",
      noResultsLabel: "इन फ़िल्टर से कोई डेक नहीं मिला।",
      paginationLabel: "कैटलॉग पृष्ठ",
      pageStatusTemplate: "पृष्ठ {page}, कुल {total}",
      pickerCloseLabel: "बंद करें",
      pickerDoneLabel: "हो गया",
      previousPageLabel: "पिछला पृष्ठ",
      resultCountTemplates: {
        zero: "{count} डेक",
        one: "{count} डेक",
        two: "{count} डेक",
        few: "{count} डेक",
        many: "{count} डेक",
        other: "{count} डेक",
      },
      searchLabel: "डेक खोजें",
      searchPlaceholder: "शीर्षक, लेखक, संग्रह या लक्षित शिक्षार्थियों की भाषा",
      showFiltersLabel: "खोज और फ़िल्टर",
      sortLabel: "क्रम",
      sortNewestLabel: "सबसे नए",
      sortRelevanceLabel: "प्रासंगिकता",
      sortTitleLabel: "शीर्षक",
    },
    byLabel: "लेखक",
    cardBackLabel: "उत्तर",
    cardFrontLabel: "प्रश्न",
    cardHeadingTemplate: "कार्ड {number}",
    cardPreviewsHeading: "इस डेक के कार्ड",
    cardCountTemplates: {
      zero: "{count} कार्ड",
      one: "{count} कार्ड",
      two: "{count} कार्ड",
      few: "{count} कार्ड",
      many: "{count} कार्ड",
      other: "{count} कार्ड",
    },
    cardsLabel: "कार्ड",
    contentWarningLabel: "सामग्री चेतावनी",
    coverPlaceholderLabel: "कवर पूर्वावलोकन उपलब्ध नहीं है",
    deckDetailsHeading: "डेक का विवरण",
    descriptionHeading: "इस डेक के बारे में",
    emptyLabel: "अभी तक कोई डेक प्रकाशित नहीं हुआ है।",
    installHelper: "पढ़ाई शुरू करने के लिए Nibomo खुलेगा।",
    installLabel: "इस डेक से मुफ़्त में पढ़ें",
    intro: "समुदाय द्वारा साझा किए गए सार्वजनिक फ़्लैशकार्ड डेक देखें।",
    lastUpdatedLabel: "पिछली बार अपडेट किया गया",
    languagesLabel: "लक्षित शिक्षार्थियों की भाषाएँ",
    levelLabel: "स्तर",
    licenseLabel: "लाइसेंस",
    navigationLabel: "कैटलॉग",
    noCardPreviewsLabel: "इस डेक में कोई कार्ड नहीं है।",
    publishedLabel: "प्रकाशित",
    similarDecksHeading: "मिलते-जुलते डेक",
    subjectLabel: "विषय",
    tagsLabel: "टैग",
    title: "सार्वजनिक फ़्लैशकार्ड कैटलॉग",
    versionLabel: "संस्करण",
  },
  ja: {
    breadcrumbLabel: "カタログ",
    browse: {
      allAuthorsLabel: "すべての作成者",
      allCollectionsLabel: "すべてのコレクション",
      allLanguagesLabel: "すべての言語",
      authorLabel: "作成者",
      authorSearchLabel: "作成者を検索",
      authorSearchPlaceholder: "作成者名または識別子",
      clearFiltersLabel: "フィルターをクリア",
      collectionLabel: "コレクション",
      collectionSearchLabel: "コレクションを検索",
      collectionSearchPlaceholder: "コレクション名または識別子",
      filtersLabel: "フィルター",
      languageLabel: "対象ユーザーの言語",
      languageSearchLabel: "言語を検索",
      languageSearchPlaceholder: "言語コード",
      nextPageLabel: "次のページ",
      noAuthorsFoundLabel: "作成者が見つかりません。",
      noCollectionsFoundLabel: "コレクションが見つかりません。",
      noLanguagesFoundLabel: "言語が見つかりません。",
      noResultsLabel: "この条件に一致するデッキはありません。",
      paginationLabel: "カタログのページ",
      pageStatusTemplate: "{total}ページ中{page}ページ",
      pickerCloseLabel: "閉じる",
      pickerDoneLabel: "完了",
      previousPageLabel: "前のページ",
      resultCountTemplates: {
        zero: "{count}件のデッキ",
        one: "{count}件のデッキ",
        two: "{count}件のデッキ",
        few: "{count}件のデッキ",
        many: "{count}件のデッキ",
        other: "{count}件のデッキ",
      },
      searchLabel: "デッキを検索",
      searchPlaceholder: "タイトル、作成者、コレクション、対象ユーザーの言語",
      showFiltersLabel: "検索とフィルター",
      sortLabel: "並び順",
      sortNewestLabel: "新着順",
      sortRelevanceLabel: "関連度順",
      sortTitleLabel: "タイトル順",
    },
    byLabel: "作成者",
    cardBackLabel: "回答",
    cardFrontLabel: "質問",
    cardHeadingTemplate: "カード {number}",
    cardPreviewsHeading: "このデッキのカード",
    cardCountTemplates: {
      zero: "{count}枚のカード",
      one: "{count}枚のカード",
      two: "{count}枚のカード",
      few: "{count}枚のカード",
      many: "{count}枚のカード",
      other: "{count}枚のカード",
    },
    cardsLabel: "カード",
    contentWarningLabel: "コンテンツに関する注意",
    coverPlaceholderLabel: "カバーのプレビューは利用できません",
    deckDetailsHeading: "デッキの詳細",
    descriptionHeading: "このデッキについて",
    emptyLabel: "公開済みのデッキはまだありません。",
    installHelper: "Nibomo が開き、すぐに学習を始められます。",
    installLabel: "このデッキを無料で学習",
    intro: "コミュニティが共有した公開フラッシュカードデッキを探せます。",
    lastUpdatedLabel: "最終更新",
    languagesLabel: "対象ユーザーの言語",
    levelLabel: "レベル",
    licenseLabel: "ライセンス",
    navigationLabel: "カタログ",
    noCardPreviewsLabel: "このデッキにはカードがありません。",
    publishedLabel: "公開日",
    similarDecksHeading: "類似のデッキ",
    subjectLabel: "科目",
    tagsLabel: "タグ",
    title: "公開フラッシュカードカタログ",
    versionLabel: "バージョン",
  },
  fr: {
    breadcrumbLabel: "Catalogue",
    browse: {
      allAuthorsLabel: "Tous les auteurs",
      allCollectionsLabel: "Toutes les collections",
      allLanguagesLabel: "Toutes les langues",
      authorLabel: "Auteur",
      authorSearchLabel: "Rechercher un auteur",
      authorSearchPlaceholder: "Nom ou identifiant de l'auteur",
      clearFiltersLabel: "Effacer les filtres",
      collectionLabel: "Collection",
      collectionSearchLabel: "Rechercher une collection",
      collectionSearchPlaceholder: "Nom ou identifiant de la collection",
      filtersLabel: "Filtres",
      languageLabel: "Langues du public",
      languageSearchLabel: "Rechercher une langue",
      languageSearchPlaceholder: "Code de langue",
      nextPageLabel: "Page suivante",
      noAuthorsFoundLabel: "Aucun auteur trouvé.",
      noCollectionsFoundLabel: "Aucune collection trouvée.",
      noLanguagesFoundLabel: "Aucune langue trouvée.",
      noResultsLabel: "Aucun paquet ne correspond à ces filtres.",
      paginationLabel: "Pages du catalogue",
      pageStatusTemplate: "Page {page} sur {total}",
      pickerCloseLabel: "Fermer",
      pickerDoneLabel: "Terminé",
      previousPageLabel: "Page précédente",
      resultCountTemplates: {
        zero: "{count} paquet",
        one: "{count} paquet",
        two: "{count} paquets",
        few: "{count} paquets",
        many: "{count} paquets",
        other: "{count} paquets",
      },
      searchLabel: "Rechercher un paquet",
      searchPlaceholder: "Titre, auteur, collection ou langue du public",
      showFiltersLabel: "Recherche et filtres",
      sortLabel: "Trier par",
      sortNewestLabel: "Plus récents",
      sortRelevanceLabel: "Pertinence",
      sortTitleLabel: "Titre",
    },
    byLabel: "Par",
    cardBackLabel: "Réponse",
    cardFrontLabel: "Question",
    cardHeadingTemplate: "Carte {number}",
    cardPreviewsHeading: "Cartes de ce paquet",
    cardCountTemplates: {
      zero: "{count} carte",
      one: "{count} carte",
      two: "{count} cartes",
      few: "{count} cartes",
      many: "{count} cartes",
      other: "{count} cartes",
    },
    cardsLabel: "Cartes",
    contentWarningLabel: "Avertissement sur le contenu",
    coverPlaceholderLabel: "Aperçu de la couverture indisponible",
    deckDetailsHeading: "Détails du paquet",
    descriptionHeading: "À propos de ce paquet",
    emptyLabel: "Aucun paquet n'a encore été publié.",
    installHelper: "Nibomo s'ouvre pour que vous puissiez commencer à réviser.",
    installLabel: "Réviser ce paquet gratuitement",
    intro: "Parcourez les paquets de cartes publics partagés par la communauté.",
    lastUpdatedLabel: "Dernière mise à jour",
    languagesLabel: "Langues du public",
    levelLabel: "Niveau",
    licenseLabel: "Licence",
    navigationLabel: "Catalogue",
    noCardPreviewsLabel: "Ce paquet ne contient aucune carte.",
    publishedLabel: "Publié",
    similarDecksHeading: "Paquets similaires",
    subjectLabel: "Matière",
    tagsLabel: "Étiquettes",
    title: "Catalogue public de cartes mémoire",
    versionLabel: "Version",
  },
  pt: {
    breadcrumbLabel: "Catálogo",
    browse: {
      allAuthorsLabel: "Todos os autores",
      allCollectionsLabel: "Todas as coleções",
      allLanguagesLabel: "Todos os idiomas",
      authorLabel: "Autor",
      authorSearchLabel: "Buscar autores",
      authorSearchPlaceholder: "Nome ou identificador do autor",
      clearFiltersLabel: "Limpar filtros",
      collectionLabel: "Coleção",
      collectionSearchLabel: "Buscar coleções",
      collectionSearchPlaceholder: "Nome ou identificador da coleção",
      filtersLabel: "Filtros",
      languageLabel: "Idiomas do público",
      languageSearchLabel: "Buscar idiomas",
      languageSearchPlaceholder: "Código do idioma",
      nextPageLabel: "Próxima página",
      noAuthorsFoundLabel: "Nenhum autor encontrado.",
      noCollectionsFoundLabel: "Nenhuma coleção encontrada.",
      noLanguagesFoundLabel: "Nenhum idioma encontrado.",
      noResultsLabel: "Nenhum baralho corresponde a esses filtros.",
      paginationLabel: "Páginas do catálogo",
      pageStatusTemplate: "Página {page} de {total}",
      pickerCloseLabel: "Fechar",
      pickerDoneLabel: "Concluir",
      previousPageLabel: "Página anterior",
      resultCountTemplates: {
        zero: "{count} baralho",
        one: "{count} baralho",
        two: "{count} baralhos",
        few: "{count} baralhos",
        many: "{count} baralhos",
        other: "{count} baralhos",
      },
      searchLabel: "Buscar baralhos",
      searchPlaceholder: "Título, autor, coleção ou idioma do público",
      showFiltersLabel: "Busca e filtros",
      sortLabel: "Ordenar por",
      sortNewestLabel: "Mais recentes",
      sortRelevanceLabel: "Relevância",
      sortTitleLabel: "Título",
    },
    byLabel: "Por",
    cardBackLabel: "Resposta",
    cardFrontLabel: "Pergunta",
    cardHeadingTemplate: "Cartão {number}",
    cardPreviewsHeading: "Cartões deste baralho",
    cardCountTemplates: {
      zero: "{count} cartão",
      one: "{count} cartão",
      two: "{count} cartões",
      few: "{count} cartões",
      many: "{count} cartões",
      other: "{count} cartões",
    },
    cardsLabel: "Cartões",
    contentWarningLabel: "Aviso de conteúdo",
    coverPlaceholderLabel: "Prévia da capa indisponível",
    deckDetailsHeading: "Detalhes do baralho",
    descriptionHeading: "Sobre este baralho",
    emptyLabel: "Ainda não há baralhos publicados.",
    installHelper: "O Nibomo abre para você começar a estudar.",
    installLabel: "Estude este baralho de graça",
    intro: "Veja baralhos públicos de flashcards compartilhados pela comunidade.",
    lastUpdatedLabel: "Última atualização",
    languagesLabel: "Idiomas do público",
    levelLabel: "Nível",
    licenseLabel: "Licença",
    navigationLabel: "Catálogo",
    noCardPreviewsLabel: "Este baralho não tem cartões.",
    publishedLabel: "Publicado",
    similarDecksHeading: "Baralhos parecidos",
    subjectLabel: "Matéria",
    tagsLabel: "Tags",
    title: "Catálogo público de flashcards",
    versionLabel: "Versão",
  },
  ru: {
    breadcrumbLabel: "Каталог",
    browse: {
      allAuthorsLabel: "Все авторы",
      allCollectionsLabel: "Все коллекции",
      allLanguagesLabel: "Все языки",
      authorLabel: "Автор",
      authorSearchLabel: "Поиск авторов",
      authorSearchPlaceholder: "Имя или идентификатор автора",
      clearFiltersLabel: "Сбросить фильтры",
      collectionLabel: "Коллекция",
      collectionSearchLabel: "Поиск коллекций",
      collectionSearchPlaceholder: "Название или идентификатор коллекции",
      filtersLabel: "Фильтры",
      languageLabel: "Языки аудитории",
      languageSearchLabel: "Поиск языков",
      languageSearchPlaceholder: "Код языка",
      nextPageLabel: "Следующая страница",
      noAuthorsFoundLabel: "Авторы не найдены.",
      noCollectionsFoundLabel: "Коллекции не найдены.",
      noLanguagesFoundLabel: "Языки не найдены.",
      noResultsLabel: "Нет колод, соответствующих этим фильтрам.",
      paginationLabel: "Страницы каталога",
      pageStatusTemplate: "Страница {page} из {total}",
      pickerCloseLabel: "Закрыть",
      pickerDoneLabel: "Готово",
      previousPageLabel: "Предыдущая страница",
      resultCountTemplates: {
        zero: "{count} колод",
        one: "{count} колода",
        two: "{count} колоды",
        few: "{count} колоды",
        many: "{count} колод",
        other: "{count} колоды",
      },
      searchLabel: "Поиск колод",
      searchPlaceholder: "Название, автор, коллекция или язык аудитории",
      showFiltersLabel: "Поиск и фильтры",
      sortLabel: "Сортировка",
      sortNewestLabel: "Сначала новые",
      sortRelevanceLabel: "По релевантности",
      sortTitleLabel: "По названию",
    },
    byLabel: "Автор",
    cardBackLabel: "Ответ",
    cardFrontLabel: "Вопрос",
    cardHeadingTemplate: "Карточка {number}",
    cardPreviewsHeading: "Карточки в этой колоде",
    cardCountTemplates: {
      zero: "{count} карточек",
      one: "{count} карточка",
      two: "{count} карточки",
      few: "{count} карточки",
      many: "{count} карточек",
      other: "{count} карточки",
    },
    cardsLabel: "Карточки",
    contentWarningLabel: "Предупреждение о содержании",
    coverPlaceholderLabel: "Предпросмотр обложки недоступен",
    deckDetailsHeading: "Сведения о колоде",
    descriptionHeading: "Об этой колоде",
    emptyLabel: "Опубликованных колод пока нет.",
    installHelper: "Откроется Nibomo, и вы сможете начать изучение.",
    installLabel: "Изучать эту колоду бесплатно",
    intro: "Просматривайте общедоступные колоды карточек от сообщества.",
    lastUpdatedLabel: "Последнее обновление",
    languagesLabel: "Языки аудитории",
    levelLabel: "Уровень",
    licenseLabel: "Лицензия",
    navigationLabel: "Каталог",
    noCardPreviewsLabel: "В этой колоде нет карточек.",
    publishedLabel: "Опубликовано",
    similarDecksHeading: "Похожие колоды",
    subjectLabel: "Предмет",
    tagsLabel: "Теги",
    title: "Открытый каталог карточек",
    versionLabel: "Версия",
  },
  zh: {
    breadcrumbLabel: "目录",
    browse: {
      allAuthorsLabel: "所有作者",
      allCollectionsLabel: "所有合集",
      allLanguagesLabel: "所有语言",
      authorLabel: "作者",
      authorSearchLabel: "搜索作者",
      authorSearchPlaceholder: "作者名称或标识符",
      clearFiltersLabel: "清除筛选条件",
      collectionLabel: "合集",
      collectionSearchLabel: "搜索合集",
      collectionSearchPlaceholder: "合集名称或标识符",
      filtersLabel: "筛选条件",
      languageLabel: "受众语言",
      languageSearchLabel: "搜索语言",
      languageSearchPlaceholder: "语言代码",
      nextPageLabel: "下一页",
      noAuthorsFoundLabel: "未找到作者。",
      noCollectionsFoundLabel: "未找到合集。",
      noLanguagesFoundLabel: "未找到语言。",
      noResultsLabel: "没有符合这些筛选条件的卡组。",
      paginationLabel: "目录页面",
      pageStatusTemplate: "第 {page} 页，共 {total} 页",
      pickerCloseLabel: "关闭",
      pickerDoneLabel: "完成",
      previousPageLabel: "上一页",
      resultCountTemplates: {
        zero: "{count} 个卡组",
        one: "{count} 个卡组",
        two: "{count} 个卡组",
        few: "{count} 个卡组",
        many: "{count} 个卡组",
        other: "{count} 个卡组",
      },
      searchLabel: "搜索卡组",
      searchPlaceholder: "标题、作者、合集或受众语言",
      showFiltersLabel: "搜索和筛选",
      sortLabel: "排序方式",
      sortNewestLabel: "最新",
      sortRelevanceLabel: "相关度",
      sortTitleLabel: "标题",
    },
    byLabel: "作者",
    cardBackLabel: "答案",
    cardFrontLabel: "问题",
    cardHeadingTemplate: "卡片 {number}",
    cardPreviewsHeading: "这套卡组中的卡片",
    cardCountTemplates: {
      zero: "{count}张卡片",
      one: "{count}张卡片",
      two: "{count}张卡片",
      few: "{count}张卡片",
      many: "{count}张卡片",
      other: "{count}张卡片",
    },
    cardsLabel: "卡片",
    contentWarningLabel: "内容警告",
    coverPlaceholderLabel: "封面预览不可用",
    deckDetailsHeading: "卡组详情",
    descriptionHeading: "关于这套卡组",
    emptyLabel: "尚未发布任何卡组。",
    installHelper: "Nibomo 将打开，你可以立即开始学习。",
    installLabel: "免费学习这套卡组",
    intro: "浏览社区分享的公开闪卡组。",
    lastUpdatedLabel: "最后更新",
    languagesLabel: "受众语言",
    levelLabel: "级别",
    licenseLabel: "许可证",
    navigationLabel: "目录",
    noCardPreviewsLabel: "这套卡组中没有卡片。",
    publishedLabel: "发布日期",
    similarDecksHeading: "相似卡组",
    subjectLabel: "科目",
    tagsLabel: "标签",
    title: "公开闪卡目录",
    versionLabel: "版本",
  },
  it: {
    breadcrumbLabel: "Catalogo",
    browse: {
      allAuthorsLabel: "Tutti gli autori",
      allCollectionsLabel: "Tutte le raccolte",
      allLanguagesLabel: "Tutte le lingue",
      authorLabel: "Autore",
      authorSearchLabel: "Cerca autori",
      authorSearchPlaceholder: "Nome o identificativo dell'autore",
      clearFiltersLabel: "Azzera i filtri",
      collectionLabel: "Raccolta",
      collectionSearchLabel: "Cerca raccolte",
      collectionSearchPlaceholder: "Nome o identificativo della raccolta",
      filtersLabel: "Filtri",
      languageLabel: "Lingue del pubblico",
      languageSearchLabel: "Cerca lingue",
      languageSearchPlaceholder: "Codice lingua",
      nextPageLabel: "Pagina successiva",
      noAuthorsFoundLabel: "Nessun autore trovato.",
      noCollectionsFoundLabel: "Nessuna raccolta trovata.",
      noLanguagesFoundLabel: "Nessuna lingua trovata.",
      noResultsLabel: "Nessun mazzo corrisponde a questi filtri.",
      paginationLabel: "Pagine del catalogo",
      pageStatusTemplate: "Pagina {page} di {total}",
      pickerCloseLabel: "Chiudi",
      pickerDoneLabel: "Fatto",
      previousPageLabel: "Pagina precedente",
      resultCountTemplates: {
        zero: "{count} mazzi",
        one: "{count} mazzo",
        two: "{count} mazzi",
        few: "{count} mazzi",
        many: "{count} mazzi",
        other: "{count} mazzi",
      },
      searchLabel: "Cerca mazzi",
      searchPlaceholder: "Titolo, autore, raccolta o lingua del pubblico",
      showFiltersLabel: "Ricerca e filtri",
      sortLabel: "Ordina per",
      sortNewestLabel: "Più recenti",
      sortRelevanceLabel: "Rilevanza",
      sortTitleLabel: "Titolo",
    },
    byLabel: "Di",
    cardBackLabel: "Risposta",
    cardFrontLabel: "Domanda",
    cardHeadingTemplate: "Carta {number}",
    cardPreviewsHeading: "Carte in questo mazzo",
    cardCountTemplates: {
      zero: "{count} carte",
      one: "{count} carta",
      two: "{count} carte",
      few: "{count} carte",
      many: "{count} carte",
      other: "{count} carte",
    },
    cardsLabel: "Carte",
    contentWarningLabel: "Avviso sui contenuti",
    coverPlaceholderLabel: "Anteprima della copertina non disponibile",
    deckDetailsHeading: "Dettagli del mazzo",
    descriptionHeading: "Informazioni su questo mazzo",
    emptyLabel: "Non è ancora stato pubblicato nessun mazzo.",
    installHelper: "Nibomo si apre e puoi iniziare a studiare.",
    installLabel: "Studia questo mazzo gratis",
    intro: "Sfoglia i mazzi di flashcard pubblici condivisi dalla community.",
    lastUpdatedLabel: "Ultimo aggiornamento",
    languagesLabel: "Lingue del pubblico",
    levelLabel: "Livello",
    licenseLabel: "Licenza",
    navigationLabel: "Catalogo",
    noCardPreviewsLabel: "Questo mazzo non contiene carte.",
    publishedLabel: "Pubblicato",
    similarDecksHeading: "Mazzi simili",
    subjectLabel: "Materia",
    tagsLabel: "Tag",
    title: "Catalogo pubblico di flashcard",
    versionLabel: "Versione",
  },
  ko: {
    breadcrumbLabel: "카탈로그",
    browse: {
      allAuthorsLabel: "모든 작성자",
      allCollectionsLabel: "모든 컬렉션",
      allLanguagesLabel: "모든 언어",
      authorLabel: "작성자",
      authorSearchLabel: "작성자 검색",
      authorSearchPlaceholder: "작성자 이름 또는 식별자",
      clearFiltersLabel: "필터 지우기",
      collectionLabel: "컬렉션",
      collectionSearchLabel: "컬렉션 검색",
      collectionSearchPlaceholder: "컬렉션 이름 또는 식별자",
      filtersLabel: "필터",
      languageLabel: "대상 언어",
      languageSearchLabel: "언어 검색",
      languageSearchPlaceholder: "언어 코드",
      nextPageLabel: "다음 페이지",
      noAuthorsFoundLabel: "작성자를 찾을 수 없습니다.",
      noCollectionsFoundLabel: "컬렉션을 찾을 수 없습니다.",
      noLanguagesFoundLabel: "언어를 찾을 수 없습니다.",
      noResultsLabel: "이 필터에 맞는 덱이 없습니다.",
      paginationLabel: "카탈로그 페이지",
      pageStatusTemplate: "{total}페이지 중 {page}페이지",
      pickerCloseLabel: "닫기",
      pickerDoneLabel: "완료",
      previousPageLabel: "이전 페이지",
      resultCountTemplates: {
        zero: "{count}개의 덱",
        one: "{count}개의 덱",
        two: "{count}개의 덱",
        few: "{count}개의 덱",
        many: "{count}개의 덱",
        other: "{count}개의 덱",
      },
      searchLabel: "덱 검색",
      searchPlaceholder: "제목, 작성자, 컬렉션 또는 대상 언어",
      showFiltersLabel: "검색 및 필터",
      sortLabel: "정렬 기준",
      sortNewestLabel: "최신순",
      sortRelevanceLabel: "관련도순",
      sortTitleLabel: "제목순",
    },
    byLabel: "작성자",
    cardBackLabel: "답변",
    cardFrontLabel: "질문",
    cardHeadingTemplate: "카드 {number}",
    cardPreviewsHeading: "이 덱의 카드",
    cardCountTemplates: {
      zero: "{count}장의 카드",
      one: "{count}장의 카드",
      two: "{count}장의 카드",
      few: "{count}장의 카드",
      many: "{count}장의 카드",
      other: "{count}장의 카드",
    },
    cardsLabel: "카드",
    contentWarningLabel: "콘텐츠 주의",
    coverPlaceholderLabel: "표지 미리 보기를 사용할 수 없음",
    deckDetailsHeading: "덱 정보",
    descriptionHeading: "이 덱 소개",
    emptyLabel: "아직 공개된 덱이 없습니다.",
    installHelper: "Nibomo가 열리고 바로 학습을 시작할 수 있습니다.",
    installLabel: "이 덱 무료로 학습하기",
    intro: "커뮤니티가 공유한 공개 플래시카드 덱을 둘러보세요.",
    lastUpdatedLabel: "마지막 업데이트",
    languagesLabel: "대상 언어",
    levelLabel: "수준",
    licenseLabel: "라이선스",
    navigationLabel: "카탈로그",
    noCardPreviewsLabel: "이 덱에는 카드가 없습니다.",
    publishedLabel: "공개일",
    similarDecksHeading: "비슷한 덱",
    subjectLabel: "주제",
    tagsLabel: "태그",
    title: "공개 플래시카드 카탈로그",
    versionLabel: "버전",
  },
  id: {
    breadcrumbLabel: "Katalog",
    browse: {
      allAuthorsLabel: "Semua penulis",
      allCollectionsLabel: "Semua koleksi",
      allLanguagesLabel: "Semua bahasa",
      authorLabel: "Penulis",
      authorSearchLabel: "Cari penulis",
      authorSearchPlaceholder: "Nama atau pengenal penulis",
      clearFiltersLabel: "Hapus filter",
      collectionLabel: "Koleksi",
      collectionSearchLabel: "Cari koleksi",
      collectionSearchPlaceholder: "Nama atau pengenal koleksi",
      filtersLabel: "Filter",
      languageLabel: "Bahasa audiens",
      languageSearchLabel: "Cari bahasa",
      languageSearchPlaceholder: "Kode bahasa",
      nextPageLabel: "Halaman berikutnya",
      noAuthorsFoundLabel: "Penulis tidak ditemukan.",
      noCollectionsFoundLabel: "Koleksi tidak ditemukan.",
      noLanguagesFoundLabel: "Bahasa tidak ditemukan.",
      noResultsLabel: "Tidak ada dek yang cocok dengan filter ini.",
      paginationLabel: "Halaman katalog",
      pageStatusTemplate: "Halaman {page} dari {total}",
      pickerCloseLabel: "Tutup",
      pickerDoneLabel: "Selesai",
      previousPageLabel: "Halaman sebelumnya",
      resultCountTemplates: {
        zero: "{count} dek",
        one: "{count} dek",
        two: "{count} dek",
        few: "{count} dek",
        many: "{count} dek",
        other: "{count} dek",
      },
      searchLabel: "Cari dek",
      searchPlaceholder: "Judul, penulis, koleksi, atau bahasa audiens",
      showFiltersLabel: "Pencarian dan filter",
      sortLabel: "Urutkan menurut",
      sortNewestLabel: "Terbaru",
      sortRelevanceLabel: "Relevansi",
      sortTitleLabel: "Judul",
    },
    byLabel: "Oleh penulis",
    cardBackLabel: "Jawaban",
    cardFrontLabel: "Pertanyaan",
    cardHeadingTemplate: "Kartu {number}",
    cardPreviewsHeading: "Kartu dalam dek ini",
    cardCountTemplates: {
      zero: "{count} kartu",
      one: "{count} kartu",
      two: "{count} kartu",
      few: "{count} kartu",
      many: "{count} kartu",
      other: "{count} kartu",
    },
    cardsLabel: "Kartu",
    contentWarningLabel: "Peringatan konten",
    coverPlaceholderLabel: "Pratinjau sampul tidak tersedia",
    deckDetailsHeading: "Detail dek",
    descriptionHeading: "Tentang dek ini",
    emptyLabel: "Belum ada dek yang dipublikasikan.",
    installHelper: "Nibomo akan terbuka agar Anda bisa mulai belajar.",
    installLabel: "Pelajari dek ini gratis",
    intro: "Jelajahi dek kartu publik yang dibagikan komunitas.",
    lastUpdatedLabel: "Terakhir diperbarui",
    languagesLabel: "Bahasa audiens",
    levelLabel: "Tingkat",
    licenseLabel: "Lisensi",
    navigationLabel: "Katalog",
    noCardPreviewsLabel: "Dek ini tidak memiliki kartu.",
    publishedLabel: "Dipublikasikan",
    similarDecksHeading: "Dek serupa",
    subjectLabel: "Mata pelajaran",
    tagsLabel: "Tag",
    title: "Katalog kartu publik",
    versionLabel: "Versi",
  },
  tr: {
    breadcrumbLabel: "Katalog",
    browse: {
      allAuthorsLabel: "Tüm yazarlar",
      allCollectionsLabel: "Tüm koleksiyonlar",
      allLanguagesLabel: "Tüm diller",
      authorLabel: "Yazar",
      authorSearchLabel: "Yazar ara",
      authorSearchPlaceholder: "Yazar adı veya tanımlayıcısı",
      clearFiltersLabel: "Filtreleri temizle",
      collectionLabel: "Koleksiyon",
      collectionSearchLabel: "Koleksiyon ara",
      collectionSearchPlaceholder: "Koleksiyon adı veya tanımlayıcısı",
      filtersLabel: "Filtreler",
      languageLabel: "Hedef kitle dilleri",
      languageSearchLabel: "Dil ara",
      languageSearchPlaceholder: "Dil kodu",
      nextPageLabel: "Sonraki sayfa",
      noAuthorsFoundLabel: "Yazar bulunamadı.",
      noCollectionsFoundLabel: "Koleksiyon bulunamadı.",
      noLanguagesFoundLabel: "Dil bulunamadı.",
      noResultsLabel: "Bu filtrelere uyan deste yok.",
      paginationLabel: "Katalog sayfaları",
      pageStatusTemplate: "Sayfa {page} / {total}",
      pickerCloseLabel: "Kapat",
      pickerDoneLabel: "Bitti",
      previousPageLabel: "Önceki sayfa",
      resultCountTemplates: {
        zero: "{count} deste",
        one: "{count} deste",
        two: "{count} deste",
        few: "{count} deste",
        many: "{count} deste",
        other: "{count} deste",
      },
      searchLabel: "Deste ara",
      searchPlaceholder: "Başlık, yazar, koleksiyon veya hedef kitle dili",
      showFiltersLabel: "Arama ve filtreler",
      sortLabel: "Sıralama",
      sortNewestLabel: "En yeni",
      sortRelevanceLabel: "İlgi düzeyi",
      sortTitleLabel: "Başlık",
    },
    byLabel: "Yazan",
    cardBackLabel: "Cevap",
    cardFrontLabel: "Soru",
    cardHeadingTemplate: "Kart {number}",
    cardPreviewsHeading: "Bu destedeki kartlar",
    cardCountTemplates: {
      zero: "{count} kart",
      one: "{count} kart",
      two: "{count} kart",
      few: "{count} kart",
      many: "{count} kart",
      other: "{count} kart",
    },
    cardsLabel: "Kartlar",
    contentWarningLabel: "İçerik uyarısı",
    coverPlaceholderLabel: "Kapak önizlemesi kullanılamıyor",
    deckDetailsHeading: "Deste ayrıntıları",
    descriptionHeading: "Bu deste hakkında",
    emptyLabel: "Henüz yayımlanmış deste yok.",
    installHelper: "Nibomo açılır ve hemen çalışmaya başlayabilirsiniz.",
    installLabel: "Bu desteyle ücretsiz çalış",
    intro: "Topluluğun paylaştığı herkese açık bilgi kartı destelerine göz atın.",
    lastUpdatedLabel: "Son güncelleme",
    languagesLabel: "Hedef kitle dilleri",
    levelLabel: "Seviye",
    licenseLabel: "Lisans",
    navigationLabel: "Katalog",
    noCardPreviewsLabel: "Bu destede kart yok.",
    publishedLabel: "Yayımlandı",
    similarDecksHeading: "Benzer desteler",
    subjectLabel: "Konu",
    tagsLabel: "Etiketler",
    title: "Herkese açık bilgi kartı kataloğu",
    versionLabel: "Sürüm",
  },
  nl: {
    breadcrumbLabel: "Catalogus",
    browse: {
      allAuthorsLabel: "Alle auteurs",
      allCollectionsLabel: "Alle collecties",
      allLanguagesLabel: "Alle talen",
      authorLabel: "Auteur",
      authorSearchLabel: "Auteurs zoeken",
      authorSearchPlaceholder: "Naam of identificatie van auteur",
      clearFiltersLabel: "Filters wissen",
      collectionLabel: "Collectie",
      collectionSearchLabel: "Collecties zoeken",
      collectionSearchPlaceholder: "Naam of identificatie van collectie",
      filtersLabel: "Filters",
      languageLabel: "Talen van de doelgroep",
      languageSearchLabel: "Talen zoeken",
      languageSearchPlaceholder: "Taalcode",
      nextPageLabel: "Volgende pagina",
      noAuthorsFoundLabel: "Geen auteurs gevonden.",
      noCollectionsFoundLabel: "Geen collecties gevonden.",
      noLanguagesFoundLabel: "Geen talen gevonden.",
      noResultsLabel: "Geen decks komen overeen met deze filters.",
      paginationLabel: "Cataloguspagina's",
      pageStatusTemplate: "Pagina {page} van {total}",
      pickerCloseLabel: "Sluiten",
      pickerDoneLabel: "Klaar",
      previousPageLabel: "Vorige pagina",
      resultCountTemplates: {
        zero: "{count} decks",
        one: "{count} deck",
        two: "{count} decks",
        few: "{count} decks",
        many: "{count} decks",
        other: "{count} decks",
      },
      searchLabel: "Decks zoeken",
      searchPlaceholder: "Titel, auteur, collectie of taal van de doelgroep",
      showFiltersLabel: "Zoeken en filteren",
      sortLabel: "Sorteren op",
      sortNewestLabel: "Nieuwste",
      sortRelevanceLabel: "Relevantie",
      sortTitleLabel: "Titel",
    },
    byLabel: "Door",
    cardBackLabel: "Antwoord",
    cardFrontLabel: "Vraag",
    cardHeadingTemplate: "Kaart {number}",
    cardPreviewsHeading: "Kaarten in dit deck",
    cardCountTemplates: {
      zero: "{count} kaarten",
      one: "{count} kaart",
      two: "{count} kaarten",
      few: "{count} kaarten",
      many: "{count} kaarten",
      other: "{count} kaarten",
    },
    cardsLabel: "Kaarten",
    contentWarningLabel: "Inhoudswaarschuwing",
    coverPlaceholderLabel: "Voorbeeld van omslag niet beschikbaar",
    deckDetailsHeading: "Deckdetails",
    descriptionHeading: "Over dit deck",
    emptyLabel: "Er zijn nog geen decks gepubliceerd.",
    installHelper: "Nibomo opent zodat je meteen kunt beginnen met leren.",
    installLabel: "Gratis leren met dit deck",
    intro: "Bekijk openbare decks met flashcards die de community deelt.",
    lastUpdatedLabel: "Laatst bijgewerkt",
    languagesLabel: "Talen van de doelgroep",
    levelLabel: "Niveau",
    licenseLabel: "Licentie",
    navigationLabel: "Catalogus",
    noCardPreviewsLabel: "Dit deck bevat geen kaarten.",
    publishedLabel: "Gepubliceerd",
    similarDecksHeading: "Vergelijkbare decks",
    subjectLabel: "Onderwerp",
    tagsLabel: "Tags",
    title: "Openbare flashcardcatalogus",
    versionLabel: "Versie",
  },
  pl: {
    breadcrumbLabel: "Katalog",
    browse: {
      allAuthorsLabel: "Wszyscy autorzy",
      allCollectionsLabel: "Wszystkie kolekcje",
      allLanguagesLabel: "Wszystkie języki",
      authorLabel: "Autor",
      authorSearchLabel: "Szukaj autorów",
      authorSearchPlaceholder: "Nazwa lub identyfikator autora",
      clearFiltersLabel: "Wyczyść filtry",
      collectionLabel: "Kolekcja",
      collectionSearchLabel: "Szukaj kolekcji",
      collectionSearchPlaceholder: "Nazwa lub identyfikator kolekcji",
      filtersLabel: "Filtry",
      languageLabel: "Języki odbiorców",
      languageSearchLabel: "Szukaj języków",
      languageSearchPlaceholder: "Kod języka",
      nextPageLabel: "Następna strona",
      noAuthorsFoundLabel: "Nie znaleziono autorów.",
      noCollectionsFoundLabel: "Nie znaleziono kolekcji.",
      noLanguagesFoundLabel: "Nie znaleziono języków.",
      noResultsLabel: "Żadna talia nie pasuje do tych filtrów.",
      paginationLabel: "Strony katalogu",
      pageStatusTemplate: "Strona {page} z {total}",
      pickerCloseLabel: "Zamknij",
      pickerDoneLabel: "Gotowe",
      previousPageLabel: "Poprzednia strona",
      resultCountTemplates: {
        zero: "{count} talii",
        one: "{count} talia",
        two: "{count} talie",
        few: "{count} talie",
        many: "{count} talii",
        other: "{count} talii",
      },
      searchLabel: "Szukaj talii",
      searchPlaceholder: "Tytuł, autor, kolekcja lub język odbiorców",
      showFiltersLabel: "Wyszukiwanie i filtry",
      sortLabel: "Sortuj według",
      sortNewestLabel: "Najnowsze",
      sortRelevanceLabel: "Trafność",
      sortTitleLabel: "Tytuł",
    },
    byLabel: "Autor",
    cardBackLabel: "Odpowiedź",
    cardFrontLabel: "Pytanie",
    cardHeadingTemplate: "Karta {number}",
    cardPreviewsHeading: "Karty w tej talii",
    cardCountTemplates: {
      zero: "{count} kart",
      one: "{count} karta",
      two: "{count} karty",
      few: "{count} karty",
      many: "{count} kart",
      other: "{count} karty",
    },
    cardsLabel: "Karty",
    contentWarningLabel: "Ostrzeżenie o treści",
    coverPlaceholderLabel: "Podgląd okładki niedostępny",
    deckDetailsHeading: "Szczegóły talii",
    descriptionHeading: "O tej talii",
    emptyLabel: "Nie opublikowano jeszcze żadnych talii.",
    installHelper: "Otworzy się Nibomo, żeby od razu zacząć naukę.",
    installLabel: "Ucz się z tej talii za darmo",
    intro: "Przeglądaj publiczne talie fiszek udostępnione przez społeczność.",
    lastUpdatedLabel: "Ostatnia aktualizacja",
    languagesLabel: "Języki odbiorców",
    levelLabel: "Poziom",
    licenseLabel: "Licencja",
    navigationLabel: "Katalog",
    noCardPreviewsLabel: "Ta talia nie ma kart.",
    publishedLabel: "Opublikowano",
    similarDecksHeading: "Podobne talie",
    subjectLabel: "Przedmiot",
    tagsLabel: "Tagi",
    title: "Publiczny katalog fiszek",
    versionLabel: "Wersja",
  },
  vi: {
    breadcrumbLabel: "Danh mục",
    browse: {
      allAuthorsLabel: "Tất cả tác giả",
      allCollectionsLabel: "Tất cả bộ sưu tập",
      allLanguagesLabel: "Tất cả ngôn ngữ",
      authorLabel: "Tác giả",
      authorSearchLabel: "Tìm tác giả",
      authorSearchPlaceholder: "Tên hoặc mã tác giả",
      clearFiltersLabel: "Xóa bộ lọc",
      collectionLabel: "Bộ sưu tập",
      collectionSearchLabel: "Tìm bộ sưu tập",
      collectionSearchPlaceholder: "Tên hoặc mã bộ sưu tập",
      filtersLabel: "Bộ lọc",
      languageLabel: "Ngôn ngữ người học",
      languageSearchLabel: "Tìm ngôn ngữ",
      languageSearchPlaceholder: "Mã ngôn ngữ",
      nextPageLabel: "Trang sau",
      noAuthorsFoundLabel: "Không tìm thấy tác giả nào.",
      noCollectionsFoundLabel: "Không tìm thấy bộ sưu tập nào.",
      noLanguagesFoundLabel: "Không tìm thấy ngôn ngữ nào.",
      noResultsLabel: "Không có bộ thẻ nào khớp với bộ lọc này.",
      paginationLabel: "Các trang danh mục",
      pageStatusTemplate: "Trang {page} / {total}",
      pickerCloseLabel: "Đóng",
      pickerDoneLabel: "Xong",
      previousPageLabel: "Trang trước",
      resultCountTemplates: {
        zero: "{count} bộ thẻ",
        one: "{count} bộ thẻ",
        two: "{count} bộ thẻ",
        few: "{count} bộ thẻ",
        many: "{count} bộ thẻ",
        other: "{count} bộ thẻ",
      },
      searchLabel: "Tìm bộ thẻ",
      searchPlaceholder: "Tiêu đề, tác giả, bộ sưu tập hoặc ngôn ngữ người học",
      showFiltersLabel: "Tìm kiếm và bộ lọc",
      sortLabel: "Sắp xếp theo",
      sortNewestLabel: "Mới nhất",
      sortRelevanceLabel: "Liên quan",
      sortTitleLabel: "Tiêu đề",
    },
    byLabel: "Tác giả",
    cardBackLabel: "Câu trả lời",
    cardFrontLabel: "Câu hỏi",
    cardHeadingTemplate: "Thẻ {number}",
    cardPreviewsHeading: "Thẻ trong bộ này",
    cardCountTemplates: {
      zero: "{count} thẻ",
      one: "{count} thẻ",
      two: "{count} thẻ",
      few: "{count} thẻ",
      many: "{count} thẻ",
      other: "{count} thẻ",
    },
    cardsLabel: "Thẻ",
    contentWarningLabel: "Cảnh báo nội dung",
    coverPlaceholderLabel: "Không xem trước được ảnh bìa",
    deckDetailsHeading: "Chi tiết bộ thẻ",
    descriptionHeading: "Về bộ thẻ này",
    emptyLabel: "Chưa có bộ thẻ nào được xuất bản.",
    installHelper: "Nibomo sẽ mở ra để bạn bắt đầu học.",
    installLabel: "Học bộ thẻ này miễn phí",
    intro: "Khám phá các bộ thẻ ghi nhớ công khai do cộng đồng chia sẻ.",
    lastUpdatedLabel: "Cập nhật lần cuối",
    languagesLabel: "Ngôn ngữ người học",
    levelLabel: "Cấp độ",
    licenseLabel: "Giấy phép",
    navigationLabel: "Danh mục",
    noCardPreviewsLabel: "Bộ thẻ này chưa có thẻ nào.",
    publishedLabel: "Xuất bản",
    similarDecksHeading: "Bộ thẻ tương tự",
    subjectLabel: "Chủ đề",
    tagsLabel: "Nhãn",
    title: "Danh mục thẻ ghi nhớ công khai",
    versionLabel: "Phiên bản",
  },
  th: {
    breadcrumbLabel: "แคตตาล็อก",
    browse: {
      allAuthorsLabel: "ผู้สร้างทั้งหมด",
      allCollectionsLabel: "คอลเลกชันทั้งหมด",
      allLanguagesLabel: "ภาษาทั้งหมด",
      authorLabel: "ผู้สร้าง",
      authorSearchLabel: "ค้นหาผู้สร้าง",
      authorSearchPlaceholder: "ชื่อหรือรหัสผู้สร้าง",
      clearFiltersLabel: "ล้างตัวกรอง",
      collectionLabel: "คอลเลกชัน",
      collectionSearchLabel: "ค้นหาคอลเลกชัน",
      collectionSearchPlaceholder: "ชื่อหรือรหัสคอลเลกชัน",
      filtersLabel: "ตัวกรอง",
      languageLabel: "ภาษาของผู้เรียน",
      languageSearchLabel: "ค้นหาภาษา",
      languageSearchPlaceholder: "รหัสภาษา",
      nextPageLabel: "หน้าถัดไป",
      noAuthorsFoundLabel: "ไม่พบผู้สร้าง",
      noCollectionsFoundLabel: "ไม่พบคอลเลกชัน",
      noLanguagesFoundLabel: "ไม่พบภาษา",
      noResultsLabel: "ไม่มีเด็คที่ตรงกับตัวกรองนี้",
      paginationLabel: "หน้าของแคตตาล็อก",
      pageStatusTemplate: "หน้า {page} จาก {total}",
      pickerCloseLabel: "ปิด",
      pickerDoneLabel: "เสร็จสิ้น",
      previousPageLabel: "หน้าก่อนหน้า",
      resultCountTemplates: {
        zero: "{count} เด็ค",
        one: "{count} เด็ค",
        two: "{count} เด็ค",
        few: "{count} เด็ค",
        many: "{count} เด็ค",
        other: "{count} เด็ค",
      },
      searchLabel: "ค้นหาเด็ค",
      searchPlaceholder: "ชื่อ ผู้สร้าง คอลเลกชัน หรือภาษาของผู้เรียน",
      showFiltersLabel: "ค้นหาและตัวกรอง",
      sortLabel: "เรียงตาม",
      sortNewestLabel: "ใหม่ล่าสุด",
      sortRelevanceLabel: "ความเกี่ยวข้อง",
      sortTitleLabel: "ชื่อ",
    },
    byLabel: "โดยผู้สร้าง",
    cardBackLabel: "คำตอบ",
    cardFrontLabel: "คำถาม",
    cardHeadingTemplate: "การ์ด {number}",
    cardPreviewsHeading: "การ์ดในเด็คนี้",
    cardCountTemplates: {
      zero: "{count} การ์ด",
      one: "{count} การ์ด",
      two: "{count} การ์ด",
      few: "{count} การ์ด",
      many: "{count} การ์ด",
      other: "{count} การ์ด",
    },
    cardsLabel: "การ์ด",
    contentWarningLabel: "คำเตือนเนื้อหา",
    coverPlaceholderLabel: "ไม่มีตัวอย่างหน้าปก",
    deckDetailsHeading: "รายละเอียดเด็ค",
    descriptionHeading: "เกี่ยวกับเด็คนี้",
    emptyLabel: "ยังไม่มีเด็คที่เผยแพร่",
    installHelper: "Nibomo จะเปิดขึ้นเพื่อให้คุณเริ่มเรียนได้ทันที",
    installLabel: "เรียนเด็คนี้ฟรี",
    intro: "เลือกดูเด็คการ์ดสาธารณะที่ชุมชนแบ่งปันไว้",
    lastUpdatedLabel: "อัปเดตล่าสุด",
    languagesLabel: "ภาษาของผู้เรียน",
    levelLabel: "ระดับ",
    licenseLabel: "สัญญาอนุญาต",
    navigationLabel: "แคตตาล็อก",
    noCardPreviewsLabel: "เด็คนี้ยังไม่มีการ์ด",
    publishedLabel: "เผยแพร่เมื่อ",
    similarDecksHeading: "เด็คที่คล้ายกัน",
    subjectLabel: "วิชา",
    tagsLabel: "แท็ก",
    title: "แคตตาล็อกการ์ดสาธารณะ",
    versionLabel: "เวอร์ชัน",
  },
  uk: {
    breadcrumbLabel: "Каталог",
    browse: {
      allAuthorsLabel: "Усі автори",
      allCollectionsLabel: "Усі колекції",
      allLanguagesLabel: "Усі мови",
      authorLabel: "Автор",
      authorSearchLabel: "Пошук авторів",
      authorSearchPlaceholder: "Ім'я або ідентифікатор автора",
      clearFiltersLabel: "Скинути фільтри",
      collectionLabel: "Колекція",
      collectionSearchLabel: "Пошук колекцій",
      collectionSearchPlaceholder: "Назва або ідентифікатор колекції",
      filtersLabel: "Фільтри",
      languageLabel: "Мови аудиторії",
      languageSearchLabel: "Пошук мов",
      languageSearchPlaceholder: "Код мови",
      nextPageLabel: "Наступна сторінка",
      noAuthorsFoundLabel: "Авторів не знайдено.",
      noCollectionsFoundLabel: "Колекцій не знайдено.",
      noLanguagesFoundLabel: "Мов не знайдено.",
      noResultsLabel: "Немає колод, що відповідають цим фільтрам.",
      paginationLabel: "Сторінки каталогу",
      pageStatusTemplate: "Сторінка {page} з {total}",
      pickerCloseLabel: "Закрити",
      pickerDoneLabel: "Готово",
      previousPageLabel: "Попередня сторінка",
      resultCountTemplates: {
        zero: "{count} колод",
        one: "{count} колода",
        two: "{count} колоди",
        few: "{count} колоди",
        many: "{count} колод",
        other: "{count} колоди",
      },
      searchLabel: "Пошук колод",
      searchPlaceholder: "Назва, автор, колекція або мова аудиторії",
      showFiltersLabel: "Пошук і фільтри",
      sortLabel: "Сортування",
      sortNewestLabel: "Спочатку нові",
      sortRelevanceLabel: "За релевантністю",
      sortTitleLabel: "За назвою",
    },
    byLabel: "Автор",
    cardBackLabel: "Відповідь",
    cardFrontLabel: "Питання",
    cardHeadingTemplate: "Картка {number}",
    cardPreviewsHeading: "Картки в цій колоді",
    cardCountTemplates: {
      zero: "{count} карток",
      one: "{count} картка",
      two: "{count} картки",
      few: "{count} картки",
      many: "{count} карток",
      other: "{count} картки",
    },
    cardsLabel: "Картки",
    contentWarningLabel: "Попередження про вміст",
    coverPlaceholderLabel: "Попередній перегляд обкладинки недоступний",
    deckDetailsHeading: "Відомості про колоду",
    descriptionHeading: "Про цю колоду",
    emptyLabel: "Опублікованих колод поки немає.",
    installHelper: "Відкриється Nibomo, і ви зможете почати навчання.",
    installLabel: "Вивчати цю колоду безкоштовно",
    intro: "Переглядайте загальнодоступні колоди карток від спільноти.",
    lastUpdatedLabel: "Останнє оновлення",
    languagesLabel: "Мови аудиторії",
    levelLabel: "Рівень",
    licenseLabel: "Ліцензія",
    navigationLabel: "Каталог",
    noCardPreviewsLabel: "У цій колоді немає карток.",
    publishedLabel: "Опубліковано",
    similarDecksHeading: "Схожі колоди",
    subjectLabel: "Предмет",
    tagsLabel: "Теги",
    title: "Відкритий каталог карток",
    versionLabel: "Версія",
  },
  he: {
    breadcrumbLabel: "קטלוג",
    browse: {
      allAuthorsLabel: "כל המחברים",
      allCollectionsLabel: "כל האוספים",
      allLanguagesLabel: "כל השפות",
      authorLabel: "מחבר",
      authorSearchLabel: "חיפוש מחברים",
      authorSearchPlaceholder: "שם המחבר או מזהה",
      clearFiltersLabel: "ניקוי המסננים",
      collectionLabel: "אוסף",
      collectionSearchLabel: "חיפוש אוספים",
      collectionSearchPlaceholder: "שם האוסף או מזהה",
      filtersLabel: "מסננים",
      languageLabel: "שפות הקהל",
      languageSearchLabel: "חיפוש שפות",
      languageSearchPlaceholder: "קוד שפה",
      nextPageLabel: "העמוד הבא",
      noAuthorsFoundLabel: "לא נמצאו מחברים.",
      noCollectionsFoundLabel: "לא נמצאו אוספים.",
      noLanguagesFoundLabel: "לא נמצאו שפות.",
      noResultsLabel: "אין חפיסות שמתאימות למסננים האלה.",
      paginationLabel: "עמודי הקטלוג",
      pageStatusTemplate: "עמוד {page} מתוך {total}",
      pickerCloseLabel: "סגירה",
      pickerDoneLabel: "סיום",
      previousPageLabel: "העמוד הקודם",
      resultCountTemplates: {
        zero: "{count} חפיסות",
        one: "{count} חפיסה",
        two: "{count} חפיסות",
        few: "{count} חפיסות",
        many: "{count} חפיסות",
        other: "{count} חפיסות",
      },
      searchLabel: "חיפוש חפיסות",
      searchPlaceholder: "כותרת, מחבר, אוסף או שפת קהל",
      showFiltersLabel: "חיפוש ומסננים",
      sortLabel: "מיון לפי",
      sortNewestLabel: "החדשות ביותר",
      sortRelevanceLabel: "רלוונטיות",
      sortTitleLabel: "כותרת",
    },
    byLabel: "מאת",
    cardBackLabel: "תשובה",
    cardFrontLabel: "שאלה",
    cardHeadingTemplate: "כרטיס {number}",
    cardPreviewsHeading: "הכרטיסים בחפיסה הזו",
    cardCountTemplates: {
      zero: "{count} כרטיסים",
      one: "{count} כרטיס",
      two: "{count} כרטיסים",
      few: "{count} כרטיסים",
      many: "{count} כרטיסים",
      other: "{count} כרטיסים",
    },
    cardsLabel: "כרטיסים",
    contentWarningLabel: "אזהרת תוכן",
    coverPlaceholderLabel: "תצוגה מקדימה של הכריכה אינה זמינה",
    deckDetailsHeading: "פרטי החפיסה",
    descriptionHeading: "על החפיסה הזו",
    emptyLabel: "עדיין לא פורסמו חפיסות.",
    installHelper: "Nibomo תיפתח כדי שתוכל להתחיל ללמוד.",
    installLabel: "ללמוד את החפיסה הזו בחינם",
    intro: "עיין בחפיסות כרטיסים ציבוריות שהקהילה משתפת.",
    lastUpdatedLabel: "עודכן לאחרונה",
    languagesLabel: "שפות הקהל",
    levelLabel: "רמה",
    licenseLabel: "רישיון",
    navigationLabel: "קטלוג",
    noCardPreviewsLabel: "אין כרטיסים בחפיסה הזו.",
    publishedLabel: "פורסם",
    similarDecksHeading: "חפיסות דומות",
    subjectLabel: "נושא",
    tagsLabel: "תגיות",
    title: "קטלוג הכרטיסים הציבורי",
    versionLabel: "גרסה",
  },
};

export function getPublicCatalogUiCopy(
  locale: AppLocale,
): PublicCatalogUiCopy {
  return PUBLIC_CATALOG_COPY_BY_LOCALE[locale];
}

export function interpolatePublicCatalogCardHeading(
  copy: PublicCatalogUiCopy,
  formattedCardNumber: string,
): string {
  return copy.cardHeadingTemplate.replace("{number}", formattedCardNumber);
}
