import type { AppLocale } from "./localeConfig";

export interface PublicCatalogDestinationCopy {
  readonly allPackagesNavigationLabel: string;
  readonly authorNoPackagesLabel: string;
  readonly authorPackagesHeadingTemplate: string;
  readonly authorWebsiteLabel: string;
  readonly authorsIntro: string;
  readonly authorsNavigationLabel: string;
  readonly authorsTitle: string;
  readonly collectionAboutHeading: string;
  readonly collectionEmptyLabel: string;
  readonly collectionPackagesHeading: string;
  readonly collectionsContainingLabel: string;
  readonly collectionsIntro: string;
  readonly collectionsNavigationLabel: string;
  readonly collectionsTitle: string;
  readonly facetPackagesHeading: string;
  readonly languageIntroTemplate: string;
  readonly languageTitleTemplate: string;
  readonly packageCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
}

const PUBLIC_CATALOG_DESTINATION_COPY_BY_LOCALE: Readonly<
  Record<AppLocale, PublicCatalogDestinationCopy>
> = {
  en: {
    allPackagesNavigationLabel: "All decks",
    authorNoPackagesLabel: "This author has no published decks.",
    authorPackagesHeadingTemplate: "Decks by {name}",
    authorWebsiteLabel: "Visit author website",
    authorsIntro: "Meet the people who publish flashcard decks for the community.",
    authorsNavigationLabel: "Authors",
    authorsTitle: "Catalog authors",
    collectionAboutHeading: "About this collection",
    collectionEmptyLabel: "This collection does not contain any decks yet.",
    collectionPackagesHeading: "Decks in this collection",
    collectionsContainingLabel: "Collections",
    collectionsIntro: "Browse curated groups of public flashcard decks.",
    collectionsNavigationLabel: "Collections",
    collectionsTitle: "Flashcard collections",
    facetPackagesHeading: "Decks",
    languageIntroTemplate: "Browse public flashcard decks tagged for learners who use {tag}.",
    languageTitleTemplate: "Flashcard decks for learners who use {tag}",
    packageCountTemplates: {
      zero: "{count} decks",
      one: "{count} deck",
      two: "{count} decks",
      few: "{count} decks",
      many: "{count} decks",
      other: "{count} decks",
    },
  },
  es: {
    allPackagesNavigationLabel: "Todos los mazos",
    authorNoPackagesLabel: "Este autor no tiene mazos publicados.",
    authorPackagesHeadingTemplate: "Mazos de {name}",
    authorWebsiteLabel: "Visitar el sitio web del autor",
    authorsIntro: "Conoce a quienes publican mazos de tarjetas para la comunidad.",
    authorsNavigationLabel: "Autores",
    authorsTitle: "Autores del catálogo",
    collectionAboutHeading: "Sobre esta colección",
    collectionEmptyLabel: "Esta colección todavía no contiene mazos.",
    collectionPackagesHeading: "Mazos de esta colección",
    collectionsContainingLabel: "Colecciones",
    collectionsIntro: "Explora grupos seleccionados de mazos públicos de tarjetas.",
    collectionsNavigationLabel: "Colecciones",
    collectionsTitle: "Colecciones de tarjetas",
    facetPackagesHeading: "Mazos",
    languageIntroTemplate: "Explora mazos públicos de tarjetas etiquetados para estudiantes que usan {tag}.",
    languageTitleTemplate: "Mazos de tarjetas para estudiantes que usan {tag}",
    packageCountTemplates: {
      zero: "{count} mazos",
      one: "{count} mazo",
      two: "{count} mazos",
      few: "{count} mazos",
      many: "{count} mazos",
      other: "{count} mazos",
    },
  },
  ar: {
    allPackagesNavigationLabel: "كل الرزم",
    authorNoPackagesLabel: "لا يملك هذا المؤلف رزمًا منشورة.",
    authorPackagesHeadingTemplate: "رزم {name}",
    authorWebsiteLabel: "زيارة موقع المؤلف",
    authorsIntro: "تعرّف على الأشخاص الذين ينشرون رزم البطاقات التعليمية للمجتمع.",
    authorsNavigationLabel: "المؤلفون",
    authorsTitle: "مؤلفو الكتالوج",
    collectionAboutHeading: "حول هذه المجموعة",
    collectionEmptyLabel: "لا تحتوي هذه المجموعة على أي رزم بعد.",
    collectionPackagesHeading: "الرزم في هذه المجموعة",
    collectionsContainingLabel: "المجموعات",
    collectionsIntro: "تصفح مجموعات منتقاة من رزم البطاقات التعليمية العامة.",
    collectionsNavigationLabel: "المجموعات",
    collectionsTitle: "مجموعات البطاقات التعليمية",
    facetPackagesHeading: "الرزم",
    languageIntroTemplate: "تصفح رزم البطاقات التعليمية العامة الموسومة للمتعلمين الذين يستخدمون {tag}.",
    languageTitleTemplate: "رزم بطاقات تعليمية للمتعلمين الذين يستخدمون {tag}",
    packageCountTemplates: {
      zero: "{count} رزم",
      one: "رزمة واحدة",
      two: "رزمتان",
      few: "{count} رزم",
      many: "{count} رزمة",
      other: "{count} رزمة",
    },
  },
  de: {
    allPackagesNavigationLabel: "Alle Lernkartensets",
    authorNoPackagesLabel: "Dieser Autor hat keine Lernkartensets veröffentlicht.",
    authorPackagesHeadingTemplate: "Lernkartensets von {name}",
    authorWebsiteLabel: "Website des Autors besuchen",
    authorsIntro: "Lerne die Menschen kennen, die Lernkartensets für die Community veröffentlichen.",
    authorsNavigationLabel: "Autoren",
    authorsTitle: "Katalogautoren",
    collectionAboutHeading: "Über diese Sammlung",
    collectionEmptyLabel: "Diese Sammlung enthält noch keine Lernkartensets.",
    collectionPackagesHeading: "Lernkartensets in dieser Sammlung",
    collectionsContainingLabel: "Sammlungen",
    collectionsIntro: "Entdecke kuratierte Gruppen öffentlicher Lernkartensets.",
    collectionsNavigationLabel: "Sammlungen",
    collectionsTitle: "Lernkartensammlungen",
    facetPackagesHeading: "Lernkartensets",
    languageIntroTemplate: "Entdecke öffentliche Lernkartensets für Lernende, die {tag} verwenden.",
    languageTitleTemplate: "Lernkartensets für Lernende, die {tag} verwenden",
    packageCountTemplates: {
      zero: "{count} Lernkartensets",
      one: "{count} Lernkartenset",
      two: "{count} Lernkartensets",
      few: "{count} Lernkartensets",
      many: "{count} Lernkartensets",
      other: "{count} Lernkartensets",
    },
  },
  hi: {
    allPackagesNavigationLabel: "सभी डेक",
    authorNoPackagesLabel: "इस लेखक का कोई प्रकाशित डेक नहीं है।",
    authorPackagesHeadingTemplate: "{name} के डेक",
    authorWebsiteLabel: "लेखक की वेबसाइट देखें",
    authorsIntro: "समुदाय के लिए फ़्लैशकार्ड डेक प्रकाशित करने वाले लोगों से मिलें।",
    authorsNavigationLabel: "लेखक",
    authorsTitle: "कैटलॉग लेखक",
    collectionAboutHeading: "इस संग्रह के बारे में",
    collectionEmptyLabel: "इस संग्रह में अभी कोई डेक नहीं है।",
    collectionPackagesHeading: "इस संग्रह के डेक",
    collectionsContainingLabel: "संग्रह",
    collectionsIntro: "सार्वजनिक फ़्लैशकार्ड डेक के चुने हुए समूह देखें।",
    collectionsNavigationLabel: "संग्रह",
    collectionsTitle: "फ़्लैशकार्ड संग्रह",
    facetPackagesHeading: "डेक",
    languageIntroTemplate: "{tag} का उपयोग करने वाले शिक्षार्थियों के लिए टैग किए गए सार्वजनिक फ़्लैशकार्ड डेक देखें।",
    languageTitleTemplate: "{tag} का उपयोग करने वाले शिक्षार्थियों के लिए फ़्लैशकार्ड डेक",
    packageCountTemplates: {
      zero: "{count} डेक",
      one: "{count} डेक",
      two: "{count} डेक",
      few: "{count} डेक",
      many: "{count} डेक",
      other: "{count} डेक",
    },
  },
  ja: {
    allPackagesNavigationLabel: "すべてのデッキ",
    authorNoPackagesLabel: "この作成者が公開したデッキはありません。",
    authorPackagesHeadingTemplate: "{name} のデッキ",
    authorWebsiteLabel: "作成者のウェブサイトを見る",
    authorsIntro: "コミュニティ向けにフラッシュカードデッキを公開している人々を紹介します。",
    authorsNavigationLabel: "作成者",
    authorsTitle: "カタログの作成者",
    collectionAboutHeading: "このコレクションについて",
    collectionEmptyLabel: "このコレクションにはまだデッキがありません。",
    collectionPackagesHeading: "このコレクションのデッキ",
    collectionsContainingLabel: "コレクション",
    collectionsIntro: "公開フラッシュカードデッキをまとめたコレクションを探せます。",
    collectionsNavigationLabel: "コレクション",
    collectionsTitle: "フラッシュカードコレクション",
    facetPackagesHeading: "デッキ",
    languageIntroTemplate: "{tag} を使う学習者向けに設定された公開フラッシュカードデッキを探せます。",
    languageTitleTemplate: "{tag} を使う学習者向けフラッシュカードデッキ",
    packageCountTemplates: {
      zero: "{count}件のデッキ",
      one: "{count}件のデッキ",
      two: "{count}件のデッキ",
      few: "{count}件のデッキ",
      many: "{count}件のデッキ",
      other: "{count}件のデッキ",
    },
  },
  fr: {
    allPackagesNavigationLabel: "Tous les paquets",
    authorNoPackagesLabel: "Cet auteur n'a publié aucun paquet.",
    authorPackagesHeadingTemplate: "Paquets de {name}",
    authorWebsiteLabel: "Voir le site de l'auteur",
    authorsIntro: "Découvrez les personnes qui publient des paquets de cartes pour la communauté.",
    authorsNavigationLabel: "Auteurs",
    authorsTitle: "Auteurs du catalogue",
    collectionAboutHeading: "À propos de cette collection",
    collectionEmptyLabel: "Cette collection ne contient encore aucun paquet.",
    collectionPackagesHeading: "Paquets de cette collection",
    collectionsContainingLabel: "Collections",
    collectionsIntro: "Parcourez des sélections de paquets de cartes publics.",
    collectionsNavigationLabel: "Collections",
    collectionsTitle: "Collections de cartes mémoire",
    facetPackagesHeading: "Paquets",
    languageIntroTemplate: "Parcourez les paquets de cartes publics destinés aux apprenants qui utilisent {tag}.",
    languageTitleTemplate: "Paquets de cartes pour les apprenants qui utilisent {tag}",
    packageCountTemplates: {
      zero: "{count} paquet",
      one: "{count} paquet",
      two: "{count} paquets",
      few: "{count} paquets",
      many: "{count} paquets",
      other: "{count} paquets",
    },
  },
  pt: {
    allPackagesNavigationLabel: "Todos os baralhos",
    authorNoPackagesLabel: "Este autor não tem baralhos publicados.",
    authorPackagesHeadingTemplate: "Baralhos de {name}",
    authorWebsiteLabel: "Visitar o site do autor",
    authorsIntro: "Conheça quem publica baralhos de flashcards para a comunidade.",
    authorsNavigationLabel: "Autores",
    authorsTitle: "Autores do catálogo",
    collectionAboutHeading: "Sobre esta coleção",
    collectionEmptyLabel: "Esta coleção ainda não tem baralhos.",
    collectionPackagesHeading: "Baralhos desta coleção",
    collectionsContainingLabel: "Coleções",
    collectionsIntro: "Veja grupos selecionados de baralhos públicos de flashcards.",
    collectionsNavigationLabel: "Coleções",
    collectionsTitle: "Coleções de flashcards",
    facetPackagesHeading: "Baralhos",
    languageIntroTemplate: "Veja baralhos públicos de flashcards marcados para estudantes que usam {tag}.",
    languageTitleTemplate: "Baralhos de flashcards para estudantes que usam {tag}",
    packageCountTemplates: {
      zero: "{count} baralho",
      one: "{count} baralho",
      two: "{count} baralhos",
      few: "{count} baralhos",
      many: "{count} baralhos",
      other: "{count} baralhos",
    },
  },
  ru: {
    allPackagesNavigationLabel: "Все колоды",
    authorNoPackagesLabel: "У этого автора нет опубликованных колод.",
    authorPackagesHeadingTemplate: "Колоды автора {name}",
    authorWebsiteLabel: "Перейти на сайт автора",
    authorsIntro: "Познакомьтесь с авторами, которые публикуют колоды карточек для сообщества.",
    authorsNavigationLabel: "Авторы",
    authorsTitle: "Авторы каталога",
    collectionAboutHeading: "Об этой коллекции",
    collectionEmptyLabel: "В этой коллекции пока нет колод.",
    collectionPackagesHeading: "Колоды в этой коллекции",
    collectionsContainingLabel: "Коллекции",
    collectionsIntro: "Просматривайте тематические подборки общедоступных колод карточек.",
    collectionsNavigationLabel: "Коллекции",
    collectionsTitle: "Коллекции карточек",
    facetPackagesHeading: "Колоды",
    languageIntroTemplate: "Просматривайте общедоступные колоды карточек для аудитории, использующей {tag}.",
    languageTitleTemplate: "Колоды карточек для тех, кто использует {tag}",
    packageCountTemplates: {
      zero: "{count} колод",
      one: "{count} колода",
      two: "{count} колоды",
      few: "{count} колоды",
      many: "{count} колод",
      other: "{count} колоды",
    },
  },
  zh: {
    allPackagesNavigationLabel: "所有卡组",
    authorNoPackagesLabel: "该作者尚未发布卡组。",
    authorPackagesHeadingTemplate: "{name} 的卡组",
    authorWebsiteLabel: "访问作者网站",
    authorsIntro: "了解为社区发布闪卡组的作者。",
    authorsNavigationLabel: "作者",
    authorsTitle: "目录作者",
    collectionAboutHeading: "关于此合集",
    collectionEmptyLabel: "此合集尚未包含任何卡组。",
    collectionPackagesHeading: "此合集中的卡组",
    collectionsContainingLabel: "合集",
    collectionsIntro: "浏览精心整理的公开闪卡组合集。",
    collectionsNavigationLabel: "合集",
    collectionsTitle: "闪卡合集",
    facetPackagesHeading: "卡组",
    languageIntroTemplate: "浏览标记为面向使用 {tag} 的学习者的公开闪卡组。",
    languageTitleTemplate: "面向 {tag} 受众的闪卡组",
    packageCountTemplates: {
      zero: "{count}个卡组",
      one: "{count}个卡组",
      two: "{count}个卡组",
      few: "{count}个卡组",
      many: "{count}个卡组",
      other: "{count}个卡组",
    },
  },
  it: {
    allPackagesNavigationLabel: "Tutti i mazzi",
    authorNoPackagesLabel: "Questo autore non ha mazzi pubblicati.",
    authorPackagesHeadingTemplate: "Mazzi di {name}",
    authorWebsiteLabel: "Visita il sito dell'autore",
    authorsIntro: "Conosci le persone che pubblicano mazzi di flashcard per la community.",
    authorsNavigationLabel: "Autori",
    authorsTitle: "Autori del catalogo",
    collectionAboutHeading: "Informazioni su questa raccolta",
    collectionEmptyLabel: "Questa raccolta non contiene ancora nessun mazzo.",
    collectionPackagesHeading: "Mazzi in questa raccolta",
    collectionsContainingLabel: "Raccolte",
    collectionsIntro: "Sfoglia gruppi curati di mazzi di flashcard pubblici.",
    collectionsNavigationLabel: "Raccolte",
    collectionsTitle: "Raccolte di flashcard",
    facetPackagesHeading: "Mazzi",
    languageIntroTemplate: "Sfoglia i mazzi di flashcard pubblici pensati per chi studia usando {tag}.",
    languageTitleTemplate: "Mazzi di flashcard per chi studia usando {tag}",
    packageCountTemplates: {
      zero: "{count} mazzi",
      one: "{count} mazzo",
      two: "{count} mazzi",
      few: "{count} mazzi",
      many: "{count} mazzi",
      other: "{count} mazzi",
    },
  },
  ko: {
    allPackagesNavigationLabel: "모든 덱",
    authorNoPackagesLabel: "이 작성자가 공개한 덱이 없습니다.",
    authorPackagesHeadingTemplate: "{name}의 덱",
    authorWebsiteLabel: "작성자 웹사이트 방문",
    authorsIntro: "커뮤니티를 위해 플래시카드 덱을 공개하는 사람들을 만나 보세요.",
    authorsNavigationLabel: "작성자",
    authorsTitle: "카탈로그 작성자",
    collectionAboutHeading: "이 컬렉션 소개",
    collectionEmptyLabel: "이 컬렉션에는 아직 덱이 없습니다.",
    collectionPackagesHeading: "이 컬렉션의 덱",
    collectionsContainingLabel: "컬렉션",
    collectionsIntro: "엄선한 공개 플래시카드 덱 모음을 둘러보세요.",
    collectionsNavigationLabel: "컬렉션",
    collectionsTitle: "플래시카드 컬렉션",
    facetPackagesHeading: "덱",
    languageIntroTemplate: "{tag}을(를) 사용하는 학습자를 위해 태그된 공개 플래시카드 덱을 둘러보세요.",
    languageTitleTemplate: "{tag}을(를) 사용하는 학습자를 위한 플래시카드 덱",
    packageCountTemplates: {
      zero: "{count}개의 덱",
      one: "{count}개의 덱",
      two: "{count}개의 덱",
      few: "{count}개의 덱",
      many: "{count}개의 덱",
      other: "{count}개의 덱",
    },
  },
  id: {
    allPackagesNavigationLabel: "Semua dek",
    authorNoPackagesLabel: "Penulis ini belum memublikasikan dek.",
    authorPackagesHeadingTemplate: "Dek dari {name}",
    authorWebsiteLabel: "Kunjungi situs penulis",
    authorsIntro: "Kenali orang-orang yang memublikasikan dek kartu untuk komunitas.",
    authorsNavigationLabel: "Penulis",
    authorsTitle: "Penulis katalog",
    collectionAboutHeading: "Tentang koleksi ini",
    collectionEmptyLabel: "Koleksi ini belum berisi dek apa pun.",
    collectionPackagesHeading: "Dek dalam koleksi ini",
    collectionsContainingLabel: "Koleksi",
    collectionsIntro: "Jelajahi kelompok dek kartu publik yang dikurasi.",
    collectionsNavigationLabel: "Koleksi",
    collectionsTitle: "Koleksi kartu",
    facetPackagesHeading: "Dek",
    languageIntroTemplate: "Jelajahi dek kartu publik yang ditandai untuk pelajar yang menggunakan {tag}.",
    languageTitleTemplate: "Dek kartu untuk pelajar yang menggunakan {tag}",
    packageCountTemplates: {
      zero: "{count} dek",
      one: "{count} dek",
      two: "{count} dek",
      few: "{count} dek",
      many: "{count} dek",
      other: "{count} dek",
    },
  },
  tr: {
    allPackagesNavigationLabel: "Tüm desteler",
    authorNoPackagesLabel: "Bu yazarın yayımlanmış destesi yok.",
    authorPackagesHeadingTemplate: "{name} desteleri",
    authorWebsiteLabel: "Yazarın web sitesine git",
    authorsIntro: "Topluluk için bilgi kartı desteleri yayımlayan kişilerle tanışın.",
    authorsNavigationLabel: "Yazarlar",
    authorsTitle: "Katalog yazarları",
    collectionAboutHeading: "Bu koleksiyon hakkında",
    collectionEmptyLabel: "Bu koleksiyonda henüz deste yok.",
    collectionPackagesHeading: "Bu koleksiyondaki desteler",
    collectionsContainingLabel: "Koleksiyonlar",
    collectionsIntro: "Herkese açık bilgi kartı destelerinden derlenmiş koleksiyonlara göz atın.",
    collectionsNavigationLabel: "Koleksiyonlar",
    collectionsTitle: "Bilgi kartı koleksiyonları",
    facetPackagesHeading: "Desteler",
    languageIntroTemplate: "{tag} kullanan öğrenenler için etiketlenmiş herkese açık bilgi kartı destelerine göz atın.",
    languageTitleTemplate: "{tag} kullanan öğrenenler için bilgi kartı desteleri",
    packageCountTemplates: {
      zero: "{count} deste",
      one: "{count} deste",
      two: "{count} deste",
      few: "{count} deste",
      many: "{count} deste",
      other: "{count} deste",
    },
  },
  nl: {
    allPackagesNavigationLabel: "Alle decks",
    authorNoPackagesLabel: "Deze auteur heeft nog geen decks gepubliceerd.",
    authorPackagesHeadingTemplate: "Decks van {name}",
    authorWebsiteLabel: "Website van auteur bekijken",
    authorsIntro: "Maak kennis met de mensen die decks met flashcards voor de community publiceren.",
    authorsNavigationLabel: "Auteurs",
    authorsTitle: "Auteurs in de catalogus",
    collectionAboutHeading: "Over deze collectie",
    collectionEmptyLabel: "Deze collectie bevat nog geen decks.",
    collectionPackagesHeading: "Decks in deze collectie",
    collectionsContainingLabel: "Collecties",
    collectionsIntro: "Bekijk samengestelde groepen openbare decks met flashcards.",
    collectionsNavigationLabel: "Collecties",
    collectionsTitle: "Flashcardcollecties",
    facetPackagesHeading: "Decks",
    languageIntroTemplate: "Bekijk openbare decks met flashcards voor leerders die {tag} gebruiken.",
    languageTitleTemplate: "Decks met flashcards voor leerders die {tag} gebruiken",
    packageCountTemplates: {
      zero: "{count} decks",
      one: "{count} deck",
      two: "{count} decks",
      few: "{count} decks",
      many: "{count} decks",
      other: "{count} decks",
    },
  },
  pl: {
    allPackagesNavigationLabel: "Wszystkie talie",
    authorNoPackagesLabel: "Ten autor nie opublikował jeszcze żadnych talii.",
    authorPackagesHeadingTemplate: "Talie autora {name}",
    authorWebsiteLabel: "Odwiedź stronę autora",
    authorsIntro: "Poznaj osoby, które publikują talie fiszek dla społeczności.",
    authorsNavigationLabel: "Autorzy",
    authorsTitle: "Autorzy katalogu",
    collectionAboutHeading: "O tej kolekcji",
    collectionEmptyLabel: "Ta kolekcja nie zawiera jeszcze żadnych talii.",
    collectionPackagesHeading: "Talie w tej kolekcji",
    collectionsContainingLabel: "Kolekcje",
    collectionsIntro: "Przeglądaj tematyczne zestawy publicznych talii fiszek.",
    collectionsNavigationLabel: "Kolekcje",
    collectionsTitle: "Kolekcje fiszek",
    facetPackagesHeading: "Talie",
    languageIntroTemplate: "Przeglądaj publiczne talie fiszek oznaczone dla uczących się, którzy używają {tag}.",
    languageTitleTemplate: "Talie fiszek dla uczących się, którzy używają {tag}",
    packageCountTemplates: {
      zero: "{count} talii",
      one: "{count} talia",
      two: "{count} talie",
      few: "{count} talie",
      many: "{count} talii",
      other: "{count} talii",
    },
  },
  vi: {
    allPackagesNavigationLabel: "Tất cả bộ thẻ",
    authorNoPackagesLabel: "Tác giả này chưa xuất bản bộ thẻ nào.",
    authorPackagesHeadingTemplate: "Bộ thẻ của {name}",
    authorWebsiteLabel: "Xem website của tác giả",
    authorsIntro: "Gặp gỡ những người xuất bản bộ thẻ ghi nhớ cho cộng đồng.",
    authorsNavigationLabel: "Tác giả",
    authorsTitle: "Tác giả trong danh mục",
    collectionAboutHeading: "Về bộ sưu tập này",
    collectionEmptyLabel: "Bộ sưu tập này chưa có bộ thẻ nào.",
    collectionPackagesHeading: "Bộ thẻ trong bộ sưu tập này",
    collectionsContainingLabel: "Bộ sưu tập",
    collectionsIntro: "Khám phá các nhóm bộ thẻ ghi nhớ công khai được tuyển chọn.",
    collectionsNavigationLabel: "Bộ sưu tập",
    collectionsTitle: "Bộ sưu tập thẻ ghi nhớ",
    facetPackagesHeading: "Bộ thẻ",
    languageIntroTemplate: "Khám phá các bộ thẻ ghi nhớ công khai dành cho người học dùng {tag}.",
    languageTitleTemplate: "Bộ thẻ ghi nhớ cho người học dùng {tag}",
    packageCountTemplates: {
      zero: "{count} bộ thẻ",
      one: "{count} bộ thẻ",
      two: "{count} bộ thẻ",
      few: "{count} bộ thẻ",
      many: "{count} bộ thẻ",
      other: "{count} bộ thẻ",
    },
  },
  th: {
    allPackagesNavigationLabel: "เด็คทั้งหมด",
    authorNoPackagesLabel: "ผู้สร้างรายนี้ยังไม่ได้เผยแพร่เด็ค",
    authorPackagesHeadingTemplate: "เด็คโดย {name}",
    authorWebsiteLabel: "ไปที่เว็บไซต์ของผู้สร้าง",
    authorsIntro: "ทำความรู้จักผู้สร้างที่เผยแพร่เด็คการ์ดให้ชุมชน",
    authorsNavigationLabel: "ผู้สร้าง",
    authorsTitle: "ผู้สร้างในแคตตาล็อก",
    collectionAboutHeading: "เกี่ยวกับคอลเลกชันนี้",
    collectionEmptyLabel: "คอลเลกชันนี้ยังไม่มีเด็ค",
    collectionPackagesHeading: "เด็คในคอลเลกชันนี้",
    collectionsContainingLabel: "คอลเลกชัน",
    collectionsIntro: "เลือกดูกลุ่มเด็คการ์ดสาธารณะที่คัดมาแล้ว",
    collectionsNavigationLabel: "คอลเลกชัน",
    collectionsTitle: "คอลเลกชันการ์ด",
    facetPackagesHeading: "เด็ค",
    languageIntroTemplate: "เลือกดูเด็คการ์ดสาธารณะที่ทำไว้สำหรับผู้เรียนที่ใช้ {tag}",
    languageTitleTemplate: "เด็คการ์ดสำหรับผู้เรียนที่ใช้ {tag}",
    packageCountTemplates: {
      zero: "{count} เด็ค",
      one: "{count} เด็ค",
      two: "{count} เด็ค",
      few: "{count} เด็ค",
      many: "{count} เด็ค",
      other: "{count} เด็ค",
    },
  },
  uk: {
    allPackagesNavigationLabel: "Усі колоди",
    authorNoPackagesLabel: "У цього автора немає опублікованих колод.",
    authorPackagesHeadingTemplate: "Колоди автора {name}",
    authorWebsiteLabel: "Перейти на сайт автора",
    authorsIntro: "Познайомтеся з авторами, які публікують колоди карток для спільноти.",
    authorsNavigationLabel: "Автори",
    authorsTitle: "Автори каталогу",
    collectionAboutHeading: "Про цю колекцію",
    collectionEmptyLabel: "У цій колекції поки немає колод.",
    collectionPackagesHeading: "Колоди в цій колекції",
    collectionsContainingLabel: "Колекції",
    collectionsIntro: "Переглядайте тематичні добірки загальнодоступних колод карток.",
    collectionsNavigationLabel: "Колекції",
    collectionsTitle: "Колекції карток",
    facetPackagesHeading: "Колоди",
    languageIntroTemplate: "Переглядайте загальнодоступні колоди карток для аудиторії, яка використовує {tag}.",
    languageTitleTemplate: "Колоди карток для тих, хто використовує {tag}",
    packageCountTemplates: {
      zero: "{count} колод",
      one: "{count} колода",
      two: "{count} колоди",
      few: "{count} колоди",
      many: "{count} колод",
      other: "{count} колоди",
    },
  },
  he: {
    allPackagesNavigationLabel: "כל החפיסות",
    authorNoPackagesLabel: "למחבר הזה אין חפיסות שפורסמו.",
    authorPackagesHeadingTemplate: "חפיסות מאת {name}",
    authorWebsiteLabel: "מעבר לאתר המחבר",
    authorsIntro: "הכר את האנשים שמפרסמים חפיסות כרטיסים לקהילה.",
    authorsNavigationLabel: "מחברים",
    authorsTitle: "המחברים בקטלוג",
    collectionAboutHeading: "על האוסף הזה",
    collectionEmptyLabel: "האוסף הזה עדיין לא כולל חפיסות.",
    collectionPackagesHeading: "החפיסות באוסף הזה",
    collectionsContainingLabel: "אוספים",
    collectionsIntro: "עיין בקבוצות נבחרות של חפיסות כרטיסים ציבוריות.",
    collectionsNavigationLabel: "אוספים",
    collectionsTitle: "אוספי כרטיסים",
    facetPackagesHeading: "חפיסות",
    languageIntroTemplate: "עיין בחפיסות כרטיסים ציבוריות שמיועדות ללומדים שמשתמשים בשפה {tag}.",
    languageTitleTemplate: "חפיסות כרטיסים ללומדים שמשתמשים בשפה {tag}",
    packageCountTemplates: {
      zero: "{count} חפיסות",
      one: "{count} חפיסה",
      two: "{count} חפיסות",
      few: "{count} חפיסות",
      many: "{count} חפיסות",
      other: "{count} חפיסות",
    },
  },
  sv: {
    allPackagesNavigationLabel: "Alla kortlekar",
    authorNoPackagesLabel: "Den här författaren har inga publicerade kortlekar.",
    authorPackagesHeadingTemplate: "Kortlekar av {name}",
    authorWebsiteLabel: "Besök författarens webbplats",
    authorsIntro: "Möt personerna som publicerar kortlekar för communityn.",
    authorsNavigationLabel: "Författare",
    authorsTitle: "Författare i katalogen",
    collectionAboutHeading: "Om den här samlingen",
    collectionEmptyLabel: "Den här samlingen innehåller inga kortlekar än.",
    collectionPackagesHeading: "Kortlekar i den här samlingen",
    collectionsContainingLabel: "Samlingar",
    collectionsIntro: "Bläddra bland utvalda grupper av publika kortlekar.",
    collectionsNavigationLabel: "Samlingar",
    collectionsTitle: "Samlingar med kortlekar",
    facetPackagesHeading: "Kortlekar",
    languageIntroTemplate: "Bläddra bland publika kortlekar som är taggade för personer som använder {tag}.",
    languageTitleTemplate: "Kortlekar för personer som använder {tag}",
    packageCountTemplates: {
      zero: "{count} kortlekar",
      one: "{count} kortlek",
      two: "{count} kortlekar",
      few: "{count} kortlekar",
      many: "{count} kortlekar",
      other: "{count} kortlekar",
    },
  },
  da: {
    allPackagesNavigationLabel: "Alle bunker",
    authorNoPackagesLabel: "Denne forfatter har ingen offentliggjorte bunker.",
    authorPackagesHeadingTemplate: "Bunker af {name}",
    authorWebsiteLabel: "Besøg forfatterens websted",
    authorsIntro: "Mød de mennesker, der offentliggør bunker med flashcards til fællesskabet.",
    authorsNavigationLabel: "Forfattere",
    authorsTitle: "Forfattere i kataloget",
    collectionAboutHeading: "Om denne samling",
    collectionEmptyLabel: "Denne samling indeholder endnu ingen bunker.",
    collectionPackagesHeading: "Bunker i denne samling",
    collectionsContainingLabel: "Samlinger",
    collectionsIntro: "Gennemse kuraterede grupper af offentlige bunker med flashcards.",
    collectionsNavigationLabel: "Samlinger",
    collectionsTitle: "Samlinger med flashcards",
    facetPackagesHeading: "Bunker",
    languageIntroTemplate: "Gennemse offentlige bunker med flashcards, der er mærket til lærende, som bruger {tag}.",
    languageTitleTemplate: "Bunker med flashcards til lærende, som bruger {tag}",
    packageCountTemplates: {
      zero: "{count} bunker",
      one: "{count} bunke",
      two: "{count} bunker",
      few: "{count} bunker",
      many: "{count} bunker",
      other: "{count} bunker",
    },
  },
  nb: {
    allPackagesNavigationLabel: "Alle kortstokker",
    authorNoPackagesLabel: "Denne forfatteren har ingen publiserte kortstokker.",
    authorPackagesHeadingTemplate: "Kortstokker av {name}",
    authorWebsiteLabel: "Besøk forfatterens nettsted",
    authorsIntro: "Bli kjent med dem som publiserer kortstokker for fellesskapet.",
    authorsNavigationLabel: "Forfattere",
    authorsTitle: "Forfattere i katalogen",
    collectionAboutHeading: "Om denne samlingen",
    collectionEmptyLabel: "Denne samlingen inneholder ingen kortstokker ennå.",
    collectionPackagesHeading: "Kortstokker i denne samlingen",
    collectionsContainingLabel: "Samlinger",
    collectionsIntro: "Bla i utvalgte grupper av offentlige kortstokker.",
    collectionsNavigationLabel: "Samlinger",
    collectionsTitle: "Samlinger med læringskort",
    facetPackagesHeading: "Kortstokker",
    languageIntroTemplate: "Bla i offentlige kortstokker som er merket for dem som lærer og bruker {tag}.",
    languageTitleTemplate: "Kortstokker for dem som lærer og bruker {tag}",
    packageCountTemplates: {
      zero: "{count} kortstokker",
      one: "{count} kortstokk",
      two: "{count} kortstokker",
      few: "{count} kortstokker",
      many: "{count} kortstokker",
      other: "{count} kortstokker",
    },
  },
  fi: {
    allPackagesNavigationLabel: "Kaikki pakat",
    authorNoPackagesLabel: "Tällä tekijällä ei ole julkaistuja pakkoja.",
    authorPackagesHeadingTemplate: "Tekijän {name} pakat",
    authorWebsiteLabel: "Siirry tekijän verkkosivustolle",
    authorsIntro: "Tutustu ihmisiin, jotka julkaisevat muistikorttipakkoja yhteisölle.",
    authorsNavigationLabel: "Tekijät",
    authorsTitle: "Katalogin tekijät",
    collectionAboutHeading: "Tietoja tästä kokoelmasta",
    collectionEmptyLabel: "Tämä kokoelma ei sisällä vielä yhtään pakkaa.",
    collectionPackagesHeading: "Tämän kokoelman pakat",
    collectionsContainingLabel: "Kokoelmat",
    collectionsIntro: "Selaa kuratoituja julkisten muistikorttipakkojen ryhmiä.",
    collectionsNavigationLabel: "Kokoelmat",
    collectionsTitle: "Muistikorttikokoelmat",
    facetPackagesHeading: "Pakat",
    languageIntroTemplate: "Selaa julkisia muistikorttipakkoja, jotka on merkitty kieltä {tag} käyttäville opiskelijoille.",
    languageTitleTemplate: "Muistikorttipakat kieltä {tag} käyttäville opiskelijoille",
    packageCountTemplates: {
      zero: "{count} pakkaa",
      one: "{count} pakka",
      two: "{count} pakkaa",
      few: "{count} pakkaa",
      many: "{count} pakkaa",
      other: "{count} pakkaa",
    },
  },
  cs: {
    allPackagesNavigationLabel: "Všechny balíčky",
    authorNoPackagesLabel: "Tento autor nemá zveřejněné žádné balíčky.",
    authorPackagesHeadingTemplate: "Balíčky od {name}",
    authorWebsiteLabel: "Navštívit web autora",
    authorsIntro: "Seznamte se s lidmi, kteří zveřejňují balíčky kartiček pro komunitu.",
    authorsNavigationLabel: "Autoři",
    authorsTitle: "Autoři v katalogu",
    collectionAboutHeading: "O této kolekci",
    collectionEmptyLabel: "Tato kolekce zatím neobsahuje žádné balíčky.",
    collectionPackagesHeading: "Balíčky v této kolekci",
    collectionsContainingLabel: "Kolekce",
    collectionsIntro: "Procházejte kurátorované skupiny veřejných balíčků kartiček.",
    collectionsNavigationLabel: "Kolekce",
    collectionsTitle: "Kolekce kartiček",
    facetPackagesHeading: "Balíčky",
    languageIntroTemplate: "Procházejte veřejné balíčky kartiček označené pro ty, kdo používají {tag}.",
    languageTitleTemplate: "Balíčky kartiček pro ty, kdo používají {tag}",
    packageCountTemplates: {
      zero: "{count} balíčků",
      one: "{count} balíček",
      two: "{count} balíčků",
      few: "{count} balíčky",
      many: "{count} balíčku",
      other: "{count} balíčků",
    },
  },
  el: {
    allPackagesNavigationLabel: "Όλες οι δέσμες",
    authorNoPackagesLabel: "Αυτός ο συντάκτης δεν έχει δημοσιευμένες δέσμες.",
    authorPackagesHeadingTemplate: "Δέσμες από {name}",
    authorWebsiteLabel: "Επισκεφθείτε τον ιστότοπο του συντάκτη",
    authorsIntro: "Γνωρίστε τα άτομα που δημοσιεύουν δέσμες καρτών για την κοινότητα.",
    authorsNavigationLabel: "Συντάκτες",
    authorsTitle: "Συντάκτες του καταλόγου",
    collectionAboutHeading: "Σχετικά με αυτήν τη συλλογή",
    collectionEmptyLabel: "Αυτή η συλλογή δεν περιέχει καμία δέσμη ακόμα.",
    collectionPackagesHeading: "Δέσμες σε αυτήν τη συλλογή",
    collectionsContainingLabel: "Συλλογές",
    collectionsIntro: "Περιηγηθείτε σε επιμελημένες ομάδες δημόσιων δεσμών καρτών.",
    collectionsNavigationLabel: "Συλλογές",
    collectionsTitle: "Συλλογές καρτών",
    facetPackagesHeading: "Δέσμες",
    languageIntroTemplate: "Περιηγηθείτε σε δημόσιες δέσμες καρτών με ετικέτα για όσους μαθαίνουν στη γλώσσα {tag}.",
    languageTitleTemplate: "Δέσμες καρτών για όσους μαθαίνουν στη γλώσσα {tag}",
    packageCountTemplates: {
      zero: "{count} δέσμες",
      one: "{count} δέσμη",
      two: "{count} δέσμες",
      few: "{count} δέσμες",
      many: "{count} δέσμες",
      other: "{count} δέσμες",
    },
  },
  ro: {
    allPackagesNavigationLabel: "Toate pachetele",
    authorNoPackagesLabel: "Acest autor nu are pachete publicate.",
    authorPackagesHeadingTemplate: "Pachete de {name}",
    authorWebsiteLabel: "Vizitează site-ul autorului",
    authorsIntro: "Cunoaște-i pe cei care publică pachete de fișe pentru comunitate.",
    authorsNavigationLabel: "Autori",
    authorsTitle: "Autorii din catalog",
    collectionAboutHeading: "Despre această colecție",
    collectionEmptyLabel: "Această colecție nu conține încă niciun pachet.",
    collectionPackagesHeading: "Pachetele din această colecție",
    collectionsContainingLabel: "Colecții",
    collectionsIntro: "Răsfoiește grupuri selectate de pachete publice de fișe.",
    collectionsNavigationLabel: "Colecții",
    collectionsTitle: "Colecții de fișe",
    facetPackagesHeading: "Pachete",
    languageIntroTemplate: "Răsfoiește pachete publice de fișe marcate pentru cei care învață în {tag}.",
    languageTitleTemplate: "Pachete de fișe pentru cei care învață în {tag}",
    packageCountTemplates: {
      zero: "{count} de pachete",
      one: "{count} pachet",
      two: "{count} pachete",
      few: "{count} pachete",
      many: "{count} de pachete",
      other: "{count} de pachete",
    },
  },
  hu: {
    allPackagesNavigationLabel: "Összes pakli",
    authorNoPackagesLabel: "Ennek a szerzőnek még nincs közzétett paklija.",
    authorPackagesHeadingTemplate: "{name} paklijai",
    authorWebsiteLabel: "A szerző webhelyének megnyitása",
    authorsIntro: "Ismerd meg azokat, akik tanulókártya-paklikat tesznek közzé a közösségnek.",
    authorsNavigationLabel: "Szerzők",
    authorsTitle: "A katalógus szerzői",
    collectionAboutHeading: "A gyűjteményről",
    collectionEmptyLabel: "Ez a gyűjtemény még nem tartalmaz paklit.",
    collectionPackagesHeading: "Paklik ebben a gyűjteményben",
    collectionsContainingLabel: "Gyűjtemények",
    collectionsIntro: "Böngéssz nyilvános tanulókártya-paklikból összeállított gyűjteményeket.",
    collectionsNavigationLabel: "Gyűjtemények",
    collectionsTitle: "Tanulókártya-gyűjtemények",
    facetPackagesHeading: "Paklik",
    languageIntroTemplate: "Böngéssz nyilvános tanulókártya-paklikat, amelyeket {tag} nyelvet használó tanulóknak jelöltek meg.",
    languageTitleTemplate: "Tanulókártya-paklik {tag} nyelvet használó tanulóknak",
    packageCountTemplates: {
      zero: "{count} pakli",
      one: "{count} pakli",
      two: "{count} pakli",
      few: "{count} pakli",
      many: "{count} pakli",
      other: "{count} pakli",
    },
  },
  fa: {
    allPackagesNavigationLabel: "همهٔ دسته‌ها",
    authorNoPackagesLabel: "این نویسنده دستهٔ منتشرشده‌ای ندارد.",
    authorPackagesHeadingTemplate: "دسته‌های {name}",
    authorWebsiteLabel: "مشاهدهٔ وب‌سایت نویسنده",
    authorsIntro: "با کسانی آشنا شوید که دسته‌های کارت آموزشی را برای جامعهٔ کاربران منتشر می‌کنند.",
    authorsNavigationLabel: "نویسندگان",
    authorsTitle: "نویسندگان کاتالوگ",
    collectionAboutHeading: "دربارهٔ این مجموعه",
    collectionEmptyLabel: "این مجموعه هنوز هیچ دسته‌ای ندارد.",
    collectionPackagesHeading: "دسته‌های این مجموعه",
    collectionsContainingLabel: "مجموعه‌ها",
    collectionsIntro: "گروه‌های گزیده‌ای از دسته‌های عمومی کارت‌های آموزشی را ببینید.",
    collectionsNavigationLabel: "مجموعه‌ها",
    collectionsTitle: "مجموعه‌های کارت‌های آموزشی",
    facetPackagesHeading: "دسته‌ها",
    languageIntroTemplate: "دسته‌های عمومی کارت‌های آموزشی را ببینید که برای یادگیرندگان با زبان {tag} برچسب خورده‌اند.",
    languageTitleTemplate: "دسته‌های کارت آموزشی برای یادگیرندگانی که از زبان {tag} استفاده می‌کنند",
    packageCountTemplates: {
      zero: "{count} دسته",
      one: "{count} دسته",
      two: "{count} دسته",
      few: "{count} دسته",
      many: "{count} دسته",
      other: "{count} دسته",
    },
  },
  ca: {
    allPackagesNavigationLabel: "Totes les baralles",
    authorNoPackagesLabel: "Aquest autor no té cap baralla publicada.",
    authorPackagesHeadingTemplate: "Baralles de {name}",
    authorWebsiteLabel: "Visita el lloc web de l'autor",
    authorsIntro: "Coneix les persones que publiquen baralles de targetes d'estudi per a la comunitat.",
    authorsNavigationLabel: "Autors",
    authorsTitle: "Autors del catàleg",
    collectionAboutHeading: "Sobre aquesta col·lecció",
    collectionEmptyLabel: "Aquesta col·lecció encara no conté cap baralla.",
    collectionPackagesHeading: "Baralles d'aquesta col·lecció",
    collectionsContainingLabel: "Col·leccions",
    collectionsIntro: "Explora grups seleccionats de baralles públiques de targetes d'estudi.",
    collectionsNavigationLabel: "Col·leccions",
    collectionsTitle: "Col·leccions de targetes d'estudi",
    facetPackagesHeading: "Baralles",
    languageIntroTemplate: "Explora baralles públiques de targetes d'estudi pensades per a qui estudia en {tag}.",
    languageTitleTemplate: "Baralles de targetes d'estudi per a qui estudia en {tag}",
    packageCountTemplates: {
      zero: "{count} baralles",
      one: "{count} baralla",
      two: "{count} baralles",
      few: "{count} baralles",
      many: "{count} baralles",
      other: "{count} baralles",
    },
  },
  bn: {
    allPackagesNavigationLabel: "সব ডেক",
    authorNoPackagesLabel: "এই লেখকের কোনো প্রকাশিত ডেক নেই।",
    authorPackagesHeadingTemplate: "{name}-এর ডেক",
    authorWebsiteLabel: "লেখকের ওয়েবসাইট দেখুন",
    authorsIntro: "যাঁরা সবার জন্য ফ্ল্যাশকার্ড ডেক প্রকাশ করেন, তাঁদের সঙ্গে পরিচিত হোন।",
    authorsNavigationLabel: "লেখক",
    authorsTitle: "ক্যাটালগের লেখক",
    collectionAboutHeading: "এই সংগ্রহ সম্পর্কে",
    collectionEmptyLabel: "এই সংগ্রহে এখনও কোনো ডেক নেই।",
    collectionPackagesHeading: "এই সংগ্রহের ডেক",
    collectionsContainingLabel: "সংগ্রহ",
    collectionsIntro: "সার্বজনীন ফ্ল্যাশকার্ড ডেকের বাছাই করা সংগ্রহ দেখুন।",
    collectionsNavigationLabel: "সংগ্রহ",
    collectionsTitle: "ফ্ল্যাশকার্ড সংগ্রহ",
    facetPackagesHeading: "ডেক",
    languageIntroTemplate: "{tag} ব্যবহার করেন এমন শিক্ষার্থীদের জন্য ট্যাগ করা সার্বজনীন ফ্ল্যাশকার্ড ডেক দেখুন।",
    languageTitleTemplate: "{tag} ব্যবহার করেন এমন শিক্ষার্থীদের জন্য ফ্ল্যাশকার্ড ডেক",
    packageCountTemplates: {
      zero: "{count}টি ডেক",
      one: "{count}টি ডেক",
      two: "{count}টি ডেক",
      few: "{count}টি ডেক",
      many: "{count}টি ডেক",
      other: "{count}টি ডেক",
    },
  },
  gu: {
    allPackagesNavigationLabel: "બધા ડેક",
    authorNoPackagesLabel: "આ લેખકનો કોઈ પ્રકાશિત ડેક નથી.",
    authorPackagesHeadingTemplate: "{name} ના ડેક",
    authorWebsiteLabel: "લેખકની વેબસાઇટ જુઓ",
    authorsIntro: "સમુદાય માટે ફ્લૅશકાર્ડ ડેક પ્રકાશિત કરનારા લોકોને મળો.",
    authorsNavigationLabel: "લેખક",
    authorsTitle: "કૅટલૉગના લેખક",
    collectionAboutHeading: "આ સંગ્રહ વિશે",
    collectionEmptyLabel: "આ સંગ્રહમાં હજી કોઈ ડેક નથી.",
    collectionPackagesHeading: "આ સંગ્રહના ડેક",
    collectionsContainingLabel: "સંગ્રહ",
    collectionsIntro: "જાહેર ફ્લૅશકાર્ડ ડેકના પસંદ કરેલા સમૂહ જુઓ.",
    collectionsNavigationLabel: "સંગ્રહ",
    collectionsTitle: "ફ્લૅશકાર્ડ સંગ્રહ",
    facetPackagesHeading: "ડેક",
    languageIntroTemplate: "{tag} વાપરતા શીખનારાઓ માટે ટૅગ કરેલા જાહેર ફ્લૅશકાર્ડ ડેક જુઓ.",
    languageTitleTemplate: "{tag} વાપરતા શીખનારાઓ માટે ફ્લૅશકાર્ડ ડેક",
    packageCountTemplates: {
      zero: "{count} ડેક",
      one: "{count} ડેક",
      two: "{count} ડેક",
      few: "{count} ડેક",
      many: "{count} ડેક",
      other: "{count} ડેક",
    },
  },
  kn: {
    allPackagesNavigationLabel: "ಎಲ್ಲ ಡೆಕ್‌ಗಳು",
    authorNoPackagesLabel: "ಈ ಲೇಖಕರ ಯಾವುದೇ ಪ್ರಕಟಿತ ಡೆಕ್ ಇಲ್ಲ.",
    authorPackagesHeadingTemplate: "{name} ಅವರ ಡೆಕ್‌ಗಳು",
    authorWebsiteLabel: "ಲೇಖಕರ ವೆಬ್‌ಸೈಟ್ ನೋಡಿ",
    authorsIntro: "ಸಮುದಾಯಕ್ಕಾಗಿ ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್ ಡೆಕ್ ಪ್ರಕಟಿಸುವವರನ್ನು ಭೇಟಿಯಾಗಿ.",
    authorsNavigationLabel: "ಲೇಖಕರು",
    authorsTitle: "ಕ್ಯಾಟಲಾಗ್ ಲೇಖಕರು",
    collectionAboutHeading: "ಈ ಸಂಗ್ರಹದ ಬಗ್ಗೆ",
    collectionEmptyLabel: "ಈ ಸಂಗ್ರಹದಲ್ಲಿ ಇನ್ನೂ ಯಾವುದೇ ಡೆಕ್ ಇಲ್ಲ.",
    collectionPackagesHeading: "ಈ ಸಂಗ್ರಹದ ಡೆಕ್‌ಗಳು",
    collectionsContainingLabel: "ಸಂಗ್ರಹಗಳು",
    collectionsIntro: "ಸಾರ್ವಜನಿಕ ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್ ಡೆಕ್‌ಗಳ ಆಯ್ದ ಗುಂಪುಗಳನ್ನು ನೋಡಿ.",
    collectionsNavigationLabel: "ಸಂಗ್ರಹಗಳು",
    collectionsTitle: "ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್ ಸಂಗ್ರಹಗಳು",
    facetPackagesHeading: "ಡೆಕ್‌ಗಳು",
    languageIntroTemplate: "{tag} ಬಳಸುವ ಕಲಿಯುವವರಿಗಾಗಿ ಟ್ಯಾಗ್ ಮಾಡಲಾದ ಸಾರ್ವಜನಿಕ ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್ ಡೆಕ್‌ಗಳನ್ನು ನೋಡಿ.",
    languageTitleTemplate: "{tag} ಬಳಸುವ ಕಲಿಯುವವರಿಗಾಗಿ ಫ್ಲ್ಯಾಶ್‌ಕಾರ್ಡ್ ಡೆಕ್‌ಗಳು",
    packageCountTemplates: {
      zero: "{count} ಡೆಕ್‌ಗಳು",
      one: "{count} ಡೆಕ್",
      two: "{count} ಡೆಕ್‌ಗಳು",
      few: "{count} ಡೆಕ್‌ಗಳು",
      many: "{count} ಡೆಕ್‌ಗಳು",
      other: "{count} ಡೆಕ್‌ಗಳು",
    },
  },
  ml: {
    allPackagesNavigationLabel: "എല്ലാ ഡെക്കുകളും",
    authorNoPackagesLabel: "ഈ രചയിതാവിന് പ്രസിദ്ധീകരിച്ച ഡെക്കുകളില്ല.",
    authorPackagesHeadingTemplate: "{name} ന്റെ ഡെക്കുകൾ",
    authorWebsiteLabel: "രചയിതാവിന്റെ വെബ്സൈറ്റ് സന്ദർശിക്കുക",
    authorsIntro: "സമൂഹത്തിനായി ഫ്ലാഷ്കാർഡ് ഡെക്കുകൾ പ്രസിദ്ധീകരിക്കുന്നവരെ പരിചയപ്പെടുക.",
    authorsNavigationLabel: "രചയിതാക്കൾ",
    authorsTitle: "കാറ്റലോഗ് രചയിതാക്കൾ",
    collectionAboutHeading: "ഈ ശേഖരത്തെക്കുറിച്ച്",
    collectionEmptyLabel: "ഈ ശേഖരത്തിൽ ഇതുവരെ ഡെക്കുകളൊന്നുമില്ല.",
    collectionPackagesHeading: "ഈ ശേഖരത്തിലെ ഡെക്കുകൾ",
    collectionsContainingLabel: "ശേഖരങ്ങൾ",
    collectionsIntro: "പൊതു ഫ്ലാഷ്കാർഡ് ഡെക്കുകളുടെ തിരഞ്ഞെടുത്ത കൂട്ടങ്ങൾ കാണുക.",
    collectionsNavigationLabel: "ശേഖരങ്ങൾ",
    collectionsTitle: "ഫ്ലാഷ്കാർഡ് ശേഖരങ്ങൾ",
    facetPackagesHeading: "ഡെക്കുകൾ",
    languageIntroTemplate: "{tag} ഉപയോഗിക്കുന്ന പഠിതാക്കൾക്കായി ടാഗ് ചെയ്ത പൊതു ഫ്ലാഷ്കാർഡ് ഡെക്കുകൾ കാണുക.",
    languageTitleTemplate: "{tag} ഉപയോഗിക്കുന്ന പഠിതാക്കൾക്കുള്ള ഫ്ലാഷ്കാർഡ് ഡെക്കുകൾ",
    packageCountTemplates: {
      zero: "{count} ഡെക്കുകൾ",
      one: "{count} ഡെക്ക്",
      two: "{count} ഡെക്കുകൾ",
      few: "{count} ഡെക്കുകൾ",
      many: "{count} ഡെക്കുകൾ",
      other: "{count} ഡെക്കുകൾ",
    },
  },
  mr: {
    allPackagesNavigationLabel: "सर्व संच",
    authorNoPackagesLabel: "या लेखकाचा कोणताही प्रकाशित संच नाही.",
    authorPackagesHeadingTemplate: "{name} यांचे संच",
    authorWebsiteLabel: "लेखकाची वेबसाइट पाहा",
    authorsIntro: "समुदायासाठी फ्लॅशकार्ड संच प्रकाशित करणाऱ्या लोकांना भेटा.",
    authorsNavigationLabel: "लेखक",
    authorsTitle: "कॅटलॉगचे लेखक",
    collectionAboutHeading: "या संग्रहाविषयी",
    collectionEmptyLabel: "या संग्रहात अजून कोणताही संच नाही.",
    collectionPackagesHeading: "या संग्रहातील संच",
    collectionsContainingLabel: "संग्रह",
    collectionsIntro: "सार्वजनिक फ्लॅशकार्ड संचांचे निवडक गट पाहा.",
    collectionsNavigationLabel: "संग्रह",
    collectionsTitle: "फ्लॅशकार्ड संग्रह",
    facetPackagesHeading: "संच",
    languageIntroTemplate: "{tag} वापरणाऱ्या शिकणाऱ्यांसाठी टॅग केलेले सार्वजनिक फ्लॅशकार्ड संच पाहा.",
    languageTitleTemplate: "{tag} वापरणाऱ्या शिकणाऱ्यांसाठी फ्लॅशकार्ड संच",
    packageCountTemplates: {
      zero: "{count} संच",
      one: "{count} संच",
      two: "{count} संच",
      few: "{count} संच",
      many: "{count} संच",
      other: "{count} संच",
    },
  },
  pa: {
    allPackagesNavigationLabel: "ਸਾਰੇ ਡੈੱਕ",
    authorNoPackagesLabel: "ਇਸ ਲੇਖਕ ਦਾ ਕੋਈ ਪ੍ਰਕਾਸ਼ਿਤ ਡੈੱਕ ਨਹੀਂ ਹੈ।",
    authorPackagesHeadingTemplate: "{name} ਦੇ ਡੈੱਕ",
    authorWebsiteLabel: "ਲੇਖਕ ਦੀ ਵੈੱਬਸਾਈਟ ਵੇਖੋ",
    authorsIntro: "ਭਾਈਚਾਰੇ ਲਈ ਫਲੈਸ਼ਕਾਰਡ ਡੈੱਕ ਪ੍ਰਕਾਸ਼ਿਤ ਕਰਨ ਵਾਲੇ ਲੋਕਾਂ ਨੂੰ ਮਿਲੋ।",
    authorsNavigationLabel: "ਲੇਖਕ",
    authorsTitle: "ਕੈਟਾਲਾਗ ਦੇ ਲੇਖਕ",
    collectionAboutHeading: "ਇਸ ਸੰਗ੍ਰਹਿ ਬਾਰੇ",
    collectionEmptyLabel: "ਇਸ ਸੰਗ੍ਰਹਿ ਵਿੱਚ ਹਾਲੇ ਕੋਈ ਡੈੱਕ ਨਹੀਂ ਹੈ।",
    collectionPackagesHeading: "ਇਸ ਸੰਗ੍ਰਹਿ ਦੇ ਡੈੱਕ",
    collectionsContainingLabel: "ਸੰਗ੍ਰਹਿ",
    collectionsIntro: "ਜਨਤਕ ਫਲੈਸ਼ਕਾਰਡ ਡੈੱਕਾਂ ਦੇ ਚੁਣੇ ਹੋਏ ਸਮੂਹ ਵੇਖੋ।",
    collectionsNavigationLabel: "ਸੰਗ੍ਰਹਿ",
    collectionsTitle: "ਫਲੈਸ਼ਕਾਰਡ ਸੰਗ੍ਰਹਿ",
    facetPackagesHeading: "ਡੈੱਕ",
    languageIntroTemplate: "{tag} ਵਰਤਣ ਵਾਲੇ ਸਿੱਖਣ ਵਾਲਿਆਂ ਲਈ ਟੈਗ ਕੀਤੇ ਜਨਤਕ ਫਲੈਸ਼ਕਾਰਡ ਡੈੱਕ ਵੇਖੋ।",
    languageTitleTemplate: "{tag} ਵਰਤਣ ਵਾਲੇ ਸਿੱਖਣ ਵਾਲਿਆਂ ਲਈ ਫਲੈਸ਼ਕਾਰਡ ਡੈੱਕ",
    packageCountTemplates: {
      zero: "{count} ਡੈੱਕ",
      one: "{count} ਡੈੱਕ",
      two: "{count} ਡੈੱਕ",
      few: "{count} ਡੈੱਕ",
      many: "{count} ਡੈੱਕ",
      other: "{count} ਡੈੱਕ",
    },
  },
  ta: {
    allPackagesNavigationLabel: "எல்லாத் தொகுப்புகளும்",
    authorNoPackagesLabel: "இந்த ஆசிரியருக்கு வெளியிடப்பட்ட தொகுப்புகள் இல்லை.",
    authorPackagesHeadingTemplate: "{name} இன் தொகுப்புகள்",
    authorWebsiteLabel: "ஆசிரியரின் இணையதளத்தைப் பாருங்கள்",
    authorsIntro: "சமூகத்துக்காக ஃபிளாஷ் கார்டு தொகுப்புகளை வெளியிடுபவர்களைச் சந்தியுங்கள்.",
    authorsNavigationLabel: "ஆசிரியர்கள்",
    authorsTitle: "பட்டியலின் ஆசிரியர்கள்",
    collectionAboutHeading: "இந்தச் சேகரிப்பு பற்றி",
    collectionEmptyLabel: "இந்தச் சேகரிப்பில் இன்னும் தொகுப்புகள் இல்லை.",
    collectionPackagesHeading: "இந்தச் சேகரிப்பின் தொகுப்புகள்",
    collectionsContainingLabel: "சேகரிப்புகள்",
    collectionsIntro: "பொது ஃபிளாஷ் கார்டு தொகுப்புகளின் தேர்ந்தெடுக்கப்பட்ட குழுக்களைப் பாருங்கள்.",
    collectionsNavigationLabel: "சேகரிப்புகள்",
    collectionsTitle: "ஃபிளாஷ் கார்டு சேகரிப்புகள்",
    facetPackagesHeading: "தொகுப்புகள்",
    languageIntroTemplate: "{tag} பயன்படுத்தும் கற்பவர்களுக்காகக் குறியிடப்பட்ட பொது ஃபிளாஷ் கார்டு தொகுப்புகளைப் பாருங்கள்.",
    languageTitleTemplate: "{tag} பயன்படுத்தும் கற்பவர்களுக்கான ஃபிளாஷ் கார்டு தொகுப்புகள்",
    packageCountTemplates: {
      zero: "{count} தொகுப்புகள்",
      one: "{count} தொகுப்பு",
      two: "{count} தொகுப்புகள்",
      few: "{count} தொகுப்புகள்",
      many: "{count} தொகுப்புகள்",
      other: "{count} தொகுப்புகள்",
    },
  },
  te: {
    allPackagesNavigationLabel: "అన్ని డెక్‌లు",
    authorNoPackagesLabel: "ఈ రచయితకు ప్రచురించిన డెక్‌లు లేవు.",
    authorPackagesHeadingTemplate: "{name} గారి డెక్‌లు",
    authorWebsiteLabel: "రచయిత వెబ్‌సైట్ చూడండి",
    authorsIntro: "సమాజం కోసం ఫ్లాష్ కార్డు డెక్‌లను ప్రచురించే వారిని కలవండి.",
    authorsNavigationLabel: "రచయితలు",
    authorsTitle: "కేటలాగ్ రచయితలు",
    collectionAboutHeading: "ఈ సంకలనం గురించి",
    collectionEmptyLabel: "ఈ సంకలనంలో ఇంకా డెక్‌లు లేవు.",
    collectionPackagesHeading: "ఈ సంకలనంలోని డెక్‌లు",
    collectionsContainingLabel: "సంకలనాలు",
    collectionsIntro: "బహిరంగ ఫ్లాష్ కార్డు డెక్‌ల ఎంపిక చేసిన సమూహాలను చూడండి.",
    collectionsNavigationLabel: "సంకలనాలు",
    collectionsTitle: "ఫ్లాష్ కార్డు సంకలనాలు",
    facetPackagesHeading: "డెక్‌లు",
    languageIntroTemplate: "{tag} ఉపయోగించే అభ్యాసకుల కోసం ట్యాగ్ చేసిన బహిరంగ ఫ్లాష్ కార్డు డెక్‌లను చూడండి.",
    languageTitleTemplate: "{tag} ఉపయోగించే అభ్యాసకుల కోసం ఫ్లాష్ కార్డు డెక్‌లు",
    packageCountTemplates: {
      zero: "{count} డెక్‌లు",
      one: "{count} డెక్",
      two: "{count} డెక్‌లు",
      few: "{count} డెక్‌లు",
      many: "{count} డెక్‌లు",
      other: "{count} డెక్‌లు",
    },
  },
  ur: {
    allPackagesNavigationLabel: "تمام ڈیک",
    authorNoPackagesLabel: "اس مصنف کا کوئی شائع شدہ ڈیک نہیں ہے۔",
    authorPackagesHeadingTemplate: "{name} کے ڈیک",
    authorWebsiteLabel: "مصنف کی ویب سائٹ دیکھیں",
    authorsIntro: "ان لوگوں سے ملیں جو کمیونٹی کے لیے فلیش کارڈ ڈیک شائع کرتے ہیں۔",
    authorsNavigationLabel: "مصنفین",
    authorsTitle: "کیٹلاگ کے مصنفین",
    collectionAboutHeading: "اس مجموعے کے بارے میں",
    collectionEmptyLabel: "اس مجموعے میں ابھی کوئی ڈیک نہیں ہے۔",
    collectionPackagesHeading: "اس مجموعے کے ڈیک",
    collectionsContainingLabel: "مجموعے",
    collectionsIntro: "عوامی فلیش کارڈ ڈیک کے منتخب گروہ دیکھیں۔",
    collectionsNavigationLabel: "مجموعے",
    collectionsTitle: "فلیش کارڈ مجموعے",
    facetPackagesHeading: "ڈیک",
    languageIntroTemplate: "{tag} استعمال کرنے والے سیکھنے والوں کے لیے ٹیگ کیے گئے عوامی فلیش کارڈ ڈیک دیکھیں۔",
    languageTitleTemplate: "{tag} استعمال کرنے والے سیکھنے والوں کے لیے فلیش کارڈ ڈیک",
    packageCountTemplates: {
      zero: "{count} ڈیک",
      one: "{count} ڈیک",
      two: "{count} ڈیکس",
      few: "{count} ڈیکس",
      many: "{count} ڈیکس",
      other: "{count} ڈیکس",
    },
  },
  sw: {
    allPackagesNavigationLabel: "Mafungu yote",
    authorNoPackagesLabel: "Mwandishi huyu hana mafungu yaliyochapishwa.",
    authorPackagesHeadingTemplate: "Mafungu ya {name}",
    authorWebsiteLabel: "Tembelea tovuti ya mwandishi",
    authorsIntro: "Kutana na watu wanaochapisha mafungu ya kadi za kujifunzia kwa ajili ya jamii.",
    authorsNavigationLabel: "Waandishi",
    authorsTitle: "Waandishi wa katalogi",
    collectionAboutHeading: "Kuhusu mkusanyiko huu",
    collectionEmptyLabel: "Mkusanyiko huu bado hauna mafungu yoyote.",
    collectionPackagesHeading: "Mafungu ya mkusanyiko huu",
    collectionsContainingLabel: "Mikusanyiko",
    collectionsIntro: "Vinjari makundi teule ya mafungu ya kadi za kujifunzia ya umma.",
    collectionsNavigationLabel: "Mikusanyiko",
    collectionsTitle: "Mikusanyiko ya kadi za kujifunzia",
    facetPackagesHeading: "Mafungu",
    languageIntroTemplate: "Vinjari mafungu ya kadi za kujifunzia ya umma yaliyowekewa lebo kwa wanaojifunza wanaotumia {tag}.",
    languageTitleTemplate: "Mafungu ya kadi za kujifunzia kwa wanaojifunza wanaotumia {tag}",
    packageCountTemplates: {
      zero: "mafungu {count}",
      one: "fungu {count}",
      two: "mafungu {count}",
      few: "mafungu {count}",
      many: "mafungu {count}",
      other: "mafungu {count}",
    },
  },
};

export function getPublicCatalogDestinationCopy(
  locale: AppLocale,
): PublicCatalogDestinationCopy {
  return PUBLIC_CATALOG_DESTINATION_COPY_BY_LOCALE[locale];
}

export function interpolatePublicCatalogCopy(
  template: string,
  placeholder: "name" | "tag",
  value: string,
): string {
  return template.replace(`{${placeholder}}`, value);
}
