import type { AppLocale } from "./localeConfig";

export interface PublicCatalogBrowseUiCopy {
  readonly allAuthorsLabel: string;
  readonly allCollectionsLabel: string;
  readonly authorLabel: string;
  readonly clearFiltersLabel: string;
  readonly collectionLabel: string;
  readonly filtersLabel: string;
  readonly languageLabel: string;
  readonly nextPageLabel: string;
  readonly noResultsLabel: string;
  readonly paginationLabel: string;
  readonly pageStatusTemplate: string;
  readonly previousPageLabel: string;
  readonly resultCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
  readonly searchLabel: string;
  readonly searchPlaceholder: string;
  readonly showFiltersLabel: string;
  readonly sortLabel: string;
  readonly sortNewestLabel: string;
  readonly sortRelevanceLabel: string;
  readonly sortTitleLabel: string;
}

export interface PublicCatalogUiCopy {
  readonly breadcrumbLabel: string;
  readonly browse: PublicCatalogBrowseUiCopy;
  readonly byLabel: string;
  readonly cardBackLabel: string;
  readonly cardFrontLabel: string;
  readonly cardHeadingTemplate: string;
  readonly cardPreviewsHeading: string;
  readonly cardCountTemplates: Readonly<Record<Intl.LDMLPluralRule, string>>;
  readonly cardsLabel: string;
  readonly contentWarningLabel: string;
  readonly coverPlaceholderLabel: string;
  readonly deckDetailsHeading: string;
  readonly descriptionHeading: string;
  readonly emptyLabel: string;
  readonly installHelper: string;
  readonly installLabel: string;
  readonly intro: string;
  readonly lastUpdatedLabel: string;
  readonly languagesLabel: string;
  readonly licenseLabel: string;
  readonly navigationLabel: string;
  readonly noCardPreviewsLabel: string;
  readonly publishedLabel: string;
  readonly tagsLabel: string;
  readonly title: string;
  readonly versionLabel: string;
}

const PUBLIC_CATALOG_COPY_BY_LOCALE: Readonly<
  Record<AppLocale, PublicCatalogUiCopy>
> = {
  en: {
    breadcrumbLabel: "Catalog",
    browse: {
      allAuthorsLabel: "All authors",
      allCollectionsLabel: "All collections",
      authorLabel: "Author",
      clearFiltersLabel: "Clear filters",
      collectionLabel: "Collection",
      filtersLabel: "Filters",
      languageLabel: "Content languages",
      nextPageLabel: "Next page",
      noResultsLabel: "No decks match these filters.",
      paginationLabel: "Catalog pages",
      pageStatusTemplate: "Page {page} of {total}",
      previousPageLabel: "Previous page",
      resultCountTemplates: {
        zero: "{count} decks",
        one: "{count} deck",
        two: "{count} decks",
        few: "{count} decks",
        many: "{count} decks",
        other: "{count} decks",
      },
      searchLabel: "Search decks",
      searchPlaceholder: "Title, author, collection, or language",
      showFiltersLabel: "Search and filters",
      sortLabel: "Sort by",
      sortNewestLabel: "Newest",
      sortRelevanceLabel: "Relevance",
      sortTitleLabel: "Title",
    },
    byLabel: "By author",
    cardBackLabel: "Answer",
    cardFrontLabel: "Question",
    cardHeadingTemplate: "Card {number}",
    cardPreviewsHeading: "Cards in this deck",
    cardCountTemplates: {
      zero: "{count} cards",
      one: "{count} card",
      two: "{count} cards",
      few: "{count} cards",
      many: "{count} cards",
      other: "{count} cards",
    },
    cardsLabel: "Cards",
    contentWarningLabel: "Content warning",
    coverPlaceholderLabel: "Cover preview unavailable",
    deckDetailsHeading: "Deck details",
    descriptionHeading: "About this deck",
    emptyLabel: "No decks have been published yet.",
    installHelper: "Flashcards opens so you can start studying.",
    installLabel: "Study this deck for free",
    intro: "Browse public flashcard decks shared by the community.",
    lastUpdatedLabel: "Last updated",
    languagesLabel: "Languages",
    licenseLabel: "License",
    navigationLabel: "Catalog",
    noCardPreviewsLabel: "This deck has no cards.",
    publishedLabel: "Published",
    tagsLabel: "Tags",
    title: "Public flashcard catalog",
    versionLabel: "Version",
  },
  es: {
    breadcrumbLabel: "Catálogo",
    browse: {
      allAuthorsLabel: "Todos los autores",
      allCollectionsLabel: "Todas las colecciones",
      authorLabel: "Autor",
      clearFiltersLabel: "Borrar filtros",
      collectionLabel: "Colección",
      filtersLabel: "Filtros",
      languageLabel: "Idiomas del contenido",
      nextPageLabel: "Página siguiente",
      noResultsLabel: "Ningún mazo coincide con estos filtros.",
      paginationLabel: "Páginas del catálogo",
      pageStatusTemplate: "Página {page} de {total}",
      previousPageLabel: "Página anterior",
      resultCountTemplates: {
        zero: "{count} mazos",
        one: "{count} mazo",
        two: "{count} mazos",
        few: "{count} mazos",
        many: "{count} mazos",
        other: "{count} mazos",
      },
      searchLabel: "Buscar mazos",
      searchPlaceholder: "Título, autor, colección o idioma",
      showFiltersLabel: "Búsqueda y filtros",
      sortLabel: "Ordenar por",
      sortNewestLabel: "Más recientes",
      sortRelevanceLabel: "Relevancia",
      sortTitleLabel: "Título",
    },
    byLabel: "Por el autor",
    cardBackLabel: "Respuesta",
    cardFrontLabel: "Pregunta",
    cardHeadingTemplate: "Tarjeta {number}",
    cardPreviewsHeading: "Tarjetas de este mazo",
    cardCountTemplates: {
      zero: "{count} tarjetas",
      one: "{count} tarjeta",
      two: "{count} tarjetas",
      few: "{count} tarjetas",
      many: "{count} tarjetas",
      other: "{count} tarjetas",
    },
    cardsLabel: "Tarjetas",
    contentWarningLabel: "Advertencia de contenido",
    coverPlaceholderLabel: "Vista previa de portada no disponible",
    deckDetailsHeading: "Detalles del mazo",
    descriptionHeading: "Sobre este mazo",
    emptyLabel: "Todavía no se ha publicado ningún mazo.",
    installHelper: "Flashcards se abrirá para que puedas empezar a estudiar.",
    installLabel: "Estudia este mazo gratis",
    intro: "Explora mazos públicos de tarjetas compartidos por la comunidad.",
    lastUpdatedLabel: "Última actualización",
    languagesLabel: "Idiomas",
    licenseLabel: "Licencia",
    navigationLabel: "Catálogo",
    noCardPreviewsLabel: "Este mazo no tiene tarjetas.",
    publishedLabel: "Publicado",
    tagsLabel: "Etiquetas",
    title: "Catálogo público de tarjetas",
    versionLabel: "Versión",
  },
  ar: {
    breadcrumbLabel: "الكتالوج",
    browse: {
      allAuthorsLabel: "كل المؤلفين",
      allCollectionsLabel: "كل المجموعات",
      authorLabel: "المؤلف",
      clearFiltersLabel: "مسح عوامل التصفية",
      collectionLabel: "المجموعة",
      filtersLabel: "عوامل التصفية",
      languageLabel: "لغات المحتوى",
      nextPageLabel: "الصفحة التالية",
      noResultsLabel: "لا توجد رزم تطابق عوامل التصفية هذه.",
      paginationLabel: "صفحات الكتالوج",
      pageStatusTemplate: "الصفحة {page} من {total}",
      previousPageLabel: "الصفحة السابقة",
      resultCountTemplates: {
        zero: "{count} رزم",
        one: "رزمة واحدة",
        two: "رزمتان",
        few: "{count} رزم",
        many: "{count} رزمة",
        other: "{count} رزمة",
      },
      searchLabel: "البحث عن رزم",
      searchPlaceholder: "العنوان أو المؤلف أو المجموعة أو اللغة",
      showFiltersLabel: "البحث وعوامل التصفية",
      sortLabel: "الترتيب حسب",
      sortNewestLabel: "الأحدث",
      sortRelevanceLabel: "الصلة",
      sortTitleLabel: "العنوان",
    },
    byLabel: "من إعداد",
    cardBackLabel: "الإجابة",
    cardFrontLabel: "السؤال",
    cardHeadingTemplate: "البطاقة {number}",
    cardPreviewsHeading: "بطاقات هذه الرزمة",
    cardCountTemplates: {
      zero: "{count} بطاقات",
      one: "بطاقة واحدة",
      two: "بطاقتان",
      few: "{count} بطاقات",
      many: "{count} بطاقة",
      other: "{count} بطاقة",
    },
    cardsLabel: "البطاقات",
    contentWarningLabel: "تحذير بشأن المحتوى",
    coverPlaceholderLabel: "معاينة الغلاف غير متاحة",
    deckDetailsHeading: "تفاصيل الرزمة",
    descriptionHeading: "حول هذه الرزمة",
    emptyLabel: "لم تُنشر أي رزم بعد.",
    installHelper: "سيفتح تطبيق Flashcards لتبدأ الدراسة.",
    installLabel: "ادرس هذه الرزمة مجانًا",
    intro: "تصفح رزم البطاقات التعليمية العامة التي يشاركها المجتمع.",
    lastUpdatedLabel: "آخر تحديث",
    languagesLabel: "اللغات",
    licenseLabel: "الترخيص",
    navigationLabel: "الكتالوج",
    noCardPreviewsLabel: "لا تحتوي هذه الرزمة على بطاقات.",
    publishedLabel: "تاريخ النشر",
    tagsLabel: "الوسوم",
    title: "كتالوج البطاقات التعليمية العام",
    versionLabel: "الإصدار",
  },
  de: {
    breadcrumbLabel: "Katalog",
    browse: {
      allAuthorsLabel: "Alle Autoren",
      allCollectionsLabel: "Alle Sammlungen",
      authorLabel: "Autor",
      clearFiltersLabel: "Filter zurücksetzen",
      collectionLabel: "Sammlung",
      filtersLabel: "Filter",
      languageLabel: "Inhaltssprachen",
      nextPageLabel: "Nächste Seite",
      noResultsLabel: "Keine Lernkartensets entsprechen diesen Filtern.",
      paginationLabel: "Katalogseiten",
      pageStatusTemplate: "Seite {page} von {total}",
      previousPageLabel: "Vorherige Seite",
      resultCountTemplates: {
        zero: "{count} Lernkartensets",
        one: "{count} Lernkartenset",
        two: "{count} Lernkartensets",
        few: "{count} Lernkartensets",
        many: "{count} Lernkartensets",
        other: "{count} Lernkartensets",
      },
      searchLabel: "Lernkartensets suchen",
      searchPlaceholder: "Titel, Autor, Sammlung oder Sprache",
      showFiltersLabel: "Suche und Filter",
      sortLabel: "Sortieren nach",
      sortNewestLabel: "Neueste",
      sortRelevanceLabel: "Relevanz",
      sortTitleLabel: "Titel",
    },
    byLabel: "Von",
    cardBackLabel: "Antwort",
    cardFrontLabel: "Frage",
    cardHeadingTemplate: "Karte {number}",
    cardPreviewsHeading: "Karten in diesem Lernkartenset",
    cardCountTemplates: {
      zero: "{count} Karten",
      one: "{count} Karte",
      two: "{count} Karten",
      few: "{count} Karten",
      many: "{count} Karten",
      other: "{count} Karten",
    },
    cardsLabel: "Karten",
    contentWarningLabel: "Inhaltswarnung",
    coverPlaceholderLabel: "Covervorschau nicht verfügbar",
    deckDetailsHeading: "Details zum Lernkartenset",
    descriptionHeading: "Über dieses Lernkartenset",
    emptyLabel: "Es wurden noch keine Lernkartensets veröffentlicht.",
    installHelper: "Flashcards wird geöffnet, damit du mit dem Lernen beginnen kannst.",
    installLabel: "Mit diesem Lernkartenset kostenlos lernen",
    intro: "Entdecke öffentliche Lernkartensets aus der Community.",
    lastUpdatedLabel: "Zuletzt aktualisiert",
    languagesLabel: "Sprachen",
    licenseLabel: "Lizenz",
    navigationLabel: "Katalog",
    noCardPreviewsLabel: "Dieses Lernkartenset enthält keine Karten.",
    publishedLabel: "Veröffentlicht",
    tagsLabel: "Tags",
    title: "Öffentlicher Lernkartenkatalog",
    versionLabel: "Version",
  },
  hi: {
    breadcrumbLabel: "कैटलॉग",
    browse: {
      allAuthorsLabel: "सभी लेखक",
      allCollectionsLabel: "सभी संग्रह",
      authorLabel: "लेखक",
      clearFiltersLabel: "फ़िल्टर हटाएँ",
      collectionLabel: "संग्रह",
      filtersLabel: "फ़िल्टर",
      languageLabel: "सामग्री की भाषाएँ",
      nextPageLabel: "अगला पृष्ठ",
      noResultsLabel: "इन फ़िल्टर से कोई डेक नहीं मिला।",
      paginationLabel: "कैटलॉग पृष्ठ",
      pageStatusTemplate: "पृष्ठ {page}, कुल {total}",
      previousPageLabel: "पिछला पृष्ठ",
      resultCountTemplates: {
        zero: "{count} डेक",
        one: "{count} डेक",
        two: "{count} डेक",
        few: "{count} डेक",
        many: "{count} डेक",
        other: "{count} डेक",
      },
      searchLabel: "डेक खोजें",
      searchPlaceholder: "शीर्षक, लेखक, संग्रह या भाषा",
      showFiltersLabel: "खोज और फ़िल्टर",
      sortLabel: "क्रम",
      sortNewestLabel: "सबसे नए",
      sortRelevanceLabel: "प्रासंगिकता",
      sortTitleLabel: "शीर्षक",
    },
    byLabel: "लेखक",
    cardBackLabel: "उत्तर",
    cardFrontLabel: "प्रश्न",
    cardHeadingTemplate: "कार्ड {number}",
    cardPreviewsHeading: "इस डेक के कार्ड",
    cardCountTemplates: {
      zero: "{count} कार्ड",
      one: "{count} कार्ड",
      two: "{count} कार्ड",
      few: "{count} कार्ड",
      many: "{count} कार्ड",
      other: "{count} कार्ड",
    },
    cardsLabel: "कार्ड",
    contentWarningLabel: "सामग्री चेतावनी",
    coverPlaceholderLabel: "कवर पूर्वावलोकन उपलब्ध नहीं है",
    deckDetailsHeading: "डेक का विवरण",
    descriptionHeading: "इस डेक के बारे में",
    emptyLabel: "अभी तक कोई डेक प्रकाशित नहीं हुआ है।",
    installHelper: "पढ़ाई शुरू करने के लिए Flashcards खुलेगा।",
    installLabel: "इस डेक से मुफ़्त में पढ़ें",
    intro: "समुदाय द्वारा साझा किए गए सार्वजनिक फ़्लैशकार्ड डेक देखें।",
    lastUpdatedLabel: "पिछली बार अपडेट किया गया",
    languagesLabel: "भाषाएँ",
    licenseLabel: "लाइसेंस",
    navigationLabel: "कैटलॉग",
    noCardPreviewsLabel: "इस डेक में कोई कार्ड नहीं है।",
    publishedLabel: "प्रकाशित",
    tagsLabel: "टैग",
    title: "सार्वजनिक फ़्लैशकार्ड कैटलॉग",
    versionLabel: "संस्करण",
  },
  ja: {
    breadcrumbLabel: "カタログ",
    browse: {
      allAuthorsLabel: "すべての作成者",
      allCollectionsLabel: "すべてのコレクション",
      authorLabel: "作成者",
      clearFiltersLabel: "フィルターをクリア",
      collectionLabel: "コレクション",
      filtersLabel: "フィルター",
      languageLabel: "コンテンツの言語",
      nextPageLabel: "次のページ",
      noResultsLabel: "この条件に一致するデッキはありません。",
      paginationLabel: "カタログのページ",
      pageStatusTemplate: "{total}ページ中{page}ページ",
      previousPageLabel: "前のページ",
      resultCountTemplates: {
        zero: "{count}件のデッキ",
        one: "{count}件のデッキ",
        two: "{count}件のデッキ",
        few: "{count}件のデッキ",
        many: "{count}件のデッキ",
        other: "{count}件のデッキ",
      },
      searchLabel: "デッキを検索",
      searchPlaceholder: "タイトル、作成者、コレクション、言語",
      showFiltersLabel: "検索とフィルター",
      sortLabel: "並び順",
      sortNewestLabel: "新着順",
      sortRelevanceLabel: "関連度順",
      sortTitleLabel: "タイトル順",
    },
    byLabel: "作成者",
    cardBackLabel: "回答",
    cardFrontLabel: "質問",
    cardHeadingTemplate: "カード {number}",
    cardPreviewsHeading: "このデッキのカード",
    cardCountTemplates: {
      zero: "{count}枚のカード",
      one: "{count}枚のカード",
      two: "{count}枚のカード",
      few: "{count}枚のカード",
      many: "{count}枚のカード",
      other: "{count}枚のカード",
    },
    cardsLabel: "カード",
    contentWarningLabel: "コンテンツに関する注意",
    coverPlaceholderLabel: "カバーのプレビューは利用できません",
    deckDetailsHeading: "デッキの詳細",
    descriptionHeading: "このデッキについて",
    emptyLabel: "公開済みのデッキはまだありません。",
    installHelper: "Flashcards が開き、すぐに学習を始められます。",
    installLabel: "このデッキを無料で学習",
    intro: "コミュニティが共有した公開フラッシュカードデッキを探せます。",
    lastUpdatedLabel: "最終更新",
    languagesLabel: "言語",
    licenseLabel: "ライセンス",
    navigationLabel: "カタログ",
    noCardPreviewsLabel: "このデッキにはカードがありません。",
    publishedLabel: "公開日",
    tagsLabel: "タグ",
    title: "公開フラッシュカードカタログ",
    versionLabel: "バージョン",
  },
  ru: {
    breadcrumbLabel: "Каталог",
    browse: {
      allAuthorsLabel: "Все авторы",
      allCollectionsLabel: "Все коллекции",
      authorLabel: "Автор",
      clearFiltersLabel: "Сбросить фильтры",
      collectionLabel: "Коллекция",
      filtersLabel: "Фильтры",
      languageLabel: "Языки содержимого",
      nextPageLabel: "Следующая страница",
      noResultsLabel: "Нет колод, соответствующих этим фильтрам.",
      paginationLabel: "Страницы каталога",
      pageStatusTemplate: "Страница {page} из {total}",
      previousPageLabel: "Предыдущая страница",
      resultCountTemplates: {
        zero: "{count} колод",
        one: "{count} колода",
        two: "{count} колоды",
        few: "{count} колоды",
        many: "{count} колод",
        other: "{count} колоды",
      },
      searchLabel: "Поиск колод",
      searchPlaceholder: "Название, автор, коллекция или язык",
      showFiltersLabel: "Поиск и фильтры",
      sortLabel: "Сортировка",
      sortNewestLabel: "Сначала новые",
      sortRelevanceLabel: "По релевантности",
      sortTitleLabel: "По названию",
    },
    byLabel: "Автор",
    cardBackLabel: "Ответ",
    cardFrontLabel: "Вопрос",
    cardHeadingTemplate: "Карточка {number}",
    cardPreviewsHeading: "Карточки в этой колоде",
    cardCountTemplates: {
      zero: "{count} карточек",
      one: "{count} карточка",
      two: "{count} карточки",
      few: "{count} карточки",
      many: "{count} карточек",
      other: "{count} карточки",
    },
    cardsLabel: "Карточки",
    contentWarningLabel: "Предупреждение о содержании",
    coverPlaceholderLabel: "Предпросмотр обложки недоступен",
    deckDetailsHeading: "Сведения о колоде",
    descriptionHeading: "Об этой колоде",
    emptyLabel: "Опубликованных колод пока нет.",
    installHelper: "Откроется Flashcards, и вы сможете начать изучение.",
    installLabel: "Изучать эту колоду бесплатно",
    intro: "Просматривайте общедоступные колоды карточек от сообщества.",
    lastUpdatedLabel: "Последнее обновление",
    languagesLabel: "Языки",
    licenseLabel: "Лицензия",
    navigationLabel: "Каталог",
    noCardPreviewsLabel: "В этой колоде нет карточек.",
    publishedLabel: "Опубликовано",
    tagsLabel: "Теги",
    title: "Открытый каталог карточек",
    versionLabel: "Версия",
  },
  zh: {
    breadcrumbLabel: "目录",
    browse: {
      allAuthorsLabel: "所有作者",
      allCollectionsLabel: "所有合集",
      authorLabel: "作者",
      clearFiltersLabel: "清除筛选条件",
      collectionLabel: "合集",
      filtersLabel: "筛选条件",
      languageLabel: "内容语言",
      nextPageLabel: "下一页",
      noResultsLabel: "没有符合这些筛选条件的卡组。",
      paginationLabel: "目录页面",
      pageStatusTemplate: "第 {page} 页，共 {total} 页",
      previousPageLabel: "上一页",
      resultCountTemplates: {
        zero: "{count} 个卡组",
        one: "{count} 个卡组",
        two: "{count} 个卡组",
        few: "{count} 个卡组",
        many: "{count} 个卡组",
        other: "{count} 个卡组",
      },
      searchLabel: "搜索卡组",
      searchPlaceholder: "标题、作者、合集或语言",
      showFiltersLabel: "搜索和筛选",
      sortLabel: "排序方式",
      sortNewestLabel: "最新",
      sortRelevanceLabel: "相关度",
      sortTitleLabel: "标题",
    },
    byLabel: "作者",
    cardBackLabel: "答案",
    cardFrontLabel: "问题",
    cardHeadingTemplate: "卡片 {number}",
    cardPreviewsHeading: "这套卡组中的卡片",
    cardCountTemplates: {
      zero: "{count}张卡片",
      one: "{count}张卡片",
      two: "{count}张卡片",
      few: "{count}张卡片",
      many: "{count}张卡片",
      other: "{count}张卡片",
    },
    cardsLabel: "卡片",
    contentWarningLabel: "内容警告",
    coverPlaceholderLabel: "封面预览不可用",
    deckDetailsHeading: "卡组详情",
    descriptionHeading: "关于这套卡组",
    emptyLabel: "尚未发布任何卡组。",
    installHelper: "Flashcards 将打开，你可以立即开始学习。",
    installLabel: "免费学习这套卡组",
    intro: "浏览社区分享的公开闪卡组。",
    lastUpdatedLabel: "最后更新",
    languagesLabel: "语言",
    licenseLabel: "许可证",
    navigationLabel: "目录",
    noCardPreviewsLabel: "这套卡组中没有卡片。",
    publishedLabel: "发布日期",
    tagsLabel: "标签",
    title: "公开闪卡目录",
    versionLabel: "版本",
  },
};

export function getPublicCatalogUiCopy(
  locale: AppLocale,
): PublicCatalogUiCopy {
  return PUBLIC_CATALOG_COPY_BY_LOCALE[locale];
}

export function interpolatePublicCatalogCardHeading(
  copy: PublicCatalogUiCopy,
  formattedCardNumber: string,
): string {
  return copy.cardHeadingTemplate.replace("{number}", formattedCardNumber);
}
